SET TERMOUT OFF
SET PAGESIZE 0
SET TRIMSPOOL ON
SET LINESIZE 75
SET FEEDBACK OFF


SET HEAD OFF;
SPOOL c:\oratemp\IntSeq.sql

prompt SPOOL c:\oratemp\IntSeq.log;


prompt DROP SEQUENCE  I_ALIASES_SEQ;;
SELECT 'CREATE SEQUENCE I_ALIASES_SEQ INCREMENT BY 1 START WITH '|| DECODE(MAX(F_RECORD_KEY)+1, NULL, 1, MAX(F_RECORD_KEY)+1) ||  ';' FROM I_ALIASES;

prompt DROP SEQUENCE  I_ATTRIBUTES_SEQ;;
SELECT 'CREATE SEQUENCE I_ATTRIBUTES_SEQ INCREMENT BY 1 START WITH '|| DECODE(MAX(F_RECORD_KEY)+1, NULL, 1, MAX(F_RECORD_KEY)+1) ||  ';' FROM I_ATTRIBUTES;

prompt DROP SEQUENCE  I_COMPONENTS_SEQ;;
SELECT 'CREATE SEQUENCE I_COMPONENTS_SEQ INCREMENT BY 1 START WITH '|| DECODE(MAX(F_RECORD_KEY)+1, NULL, 1, MAX(F_RECORD_KEY)+1) ||  ';' FROM I_COMPONENTS;

prompt DROP SEQUENCE  I_DOCUMENTS_SEQ;;
SELECT 'CREATE SEQUENCE I_DOCUMENTS_SEQ INCREMENT BY 1 START WITH '|| DECODE(MAX(F_RECORD_KEY)+1, NULL, 1, MAX(F_RECORD_KEY)+1) ||  ';' FROM I_DOCUMENTS;

prompt DROP SEQUENCE  I_ETLLOG_SEQ;;
SELECT 'CREATE SEQUENCE I_ETLLOG_SEQ INCREMENT BY 1 START WITH '|| DECODE(MAX(F_RECORD_KEY)+1, NULL, 1, MAX(F_RECORD_KEY)+1) ||  ';' FROM I_ETLLOG;

prompt DROP SEQUENCE  I_FORMULATIONS_SEQ;;
SELECT 'CREATE SEQUENCE I_FORMULATIONS_SEQ INCREMENT BY 1 START WITH '|| DECODE(MAX(F_RECORD_KEY)+1, NULL, 1, MAX(F_RECORD_KEY)+1) ||  ';' FROM I_FORMULATIONS;

prompt DROP SEQUENCE  I_LABELS_SEQ;;
SELECT 'CREATE SEQUENCE I_LABELS_SEQ INCREMENT BY 1 START WITH '|| DECODE(MAX(F_RECORD_KEY)+1, NULL, 1, MAX(F_RECORD_KEY)+1) ||  ';' FROM I_LABELS;

prompt DROP SEQUENCE  I_LABEL_DETAILS_SEQ;;
SELECT 'CREATE SEQUENCE I_LABEL_DETAILS_SEQ INCREMENT BY 1 START WITH '|| DECODE(MAX(F_RECORD_KEY)+1, NULL, 1, MAX(F_RECORD_KEY)+1) ||  ';' FROM I_LABEL_DETAILS;

prompt DROP SEQUENCE  I_LABEL_PRINTERS_SEQ;;
SELECT 'CREATE SEQUENCE I_LABEL_PRINTERS_SEQ INCREMENT BY 1 START WITH '|| DECODE(MAX(F_RECORD_KEY)+1, NULL, 1, MAX(F_RECORD_KEY)+1) ||  ';' FROM I_LABEL_PRINTERS;

prompt DROP SEQUENCE  I_LOLI_LOAD_SEQ;;
SELECT 'CREATE SEQUENCE I_LOLI_LOAD_SEQ INCREMENT BY 1 START WITH '|| DECODE(MAX(F_RECORD_KEY)+1, NULL, 1, MAX(F_RECORD_KEY)+1) ||  ';' FROM I_LOLI_LOAD;

prompt DROP SEQUENCE  I_ORDERS_SEQ;;
SELECT 'CREATE SEQUENCE I_ORDERS_SEQ INCREMENT BY 1 START WITH '|| DECODE(MAX(F_RECORD_KEY)+1, NULL, 1, MAX(F_RECORD_KEY)+1) ||  ';' FROM I_ORDERS;

prompt DROP SEQUENCE  I_PHRASES_SEQ;;
SELECT 'CREATE SEQUENCE I_PHRASES_SEQ INCREMENT BY 1 START WITH '|| DECODE(MAX(F_RECORD_KEY)+1, NULL, 1, MAX(F_RECORD_KEY)+1) ||  ';' FROM I_PHRASES;

prompt DROP SEQUENCE  I_PROCESS_SEQ;;
SELECT 'CREATE SEQUENCE I_PROCESS_SEQ INCREMENT BY 1 START WITH '|| DECODE(MAX(F_RECORD_KEY)+1, NULL, 1, MAX(F_RECORD_KEY)+1) ||  ';' FROM I_PROCESS;

prompt DROP SEQUENCE  I_PROCESSES_SEQ;;
SELECT 'CREATE SEQUENCE I_PROCESSES_SEQ INCREMENT BY 1 START WITH '|| DECODE(MAX(F_RECORD_KEY)+1, NULL, 1, MAX(F_RECORD_KEY)+1) ||  ';' FROM I_PROCESSES;

prompt DROP SEQUENCE  I_PROCESS_GROUPS_SEQ;;
SELECT 'CREATE SEQUENCE I_PROCESS_GROUPS_SEQ INCREMENT BY 1 START WITH '|| DECODE(MAX(F_RECORD_KEY)+1, NULL, 1, MAX(F_RECORD_KEY)+1) ||  ';' FROM I_PROCESS_GROUPS;

prompt DROP SEQUENCE  I_PROCESS_GROUP_MEMBERS_SEQ;;
SELECT 'CREATE SEQUENCE I_PROCESS_GROUP_MEMBERS_SEQ INCREMENT BY 1 START WITH '|| DECODE(MAX(F_RECORD_KEY)+1, NULL, 1, MAX(F_RECORD_KEY)+1) ||  ';' FROM I_PROCESS_GROUP_MEMBERS;

prompt DROP SEQUENCE  I_PRODUCTS_SEQ;;
SELECT 'CREATE SEQUENCE I_PRODUCTS_SEQ INCREMENT BY 1 START WITH '|| DECODE(MAX(F_RECORD_KEY)+1, NULL, 1, MAX(F_RECORD_KEY)+1) ||  ';' FROM I_PRODUCTS;

prompt DROP SEQUENCE  I_PRODUCT_GROUPS_SEQ;;
SELECT 'CREATE SEQUENCE I_PRODUCT_GROUPS_SEQ INCREMENT BY 1 START WITH '|| DECODE(MAX(F_RECORD_KEY)+1, NULL, 1, MAX(F_RECORD_KEY)+1) ||  ';' FROM I_PRODUCT_GROUPS;

prompt DROP SEQUENCE  I_PRODUCT_GROUP_MEMBERS_SEQ;;
SELECT 'CREATE SEQUENCE I_PRODUCT_GROUP_MEMBERS_SEQ INCREMENT BY 1 START WITH '|| DECODE(MAX(F_RECORD_KEY)+1, NULL, 1, MAX(F_RECORD_KEY)+1) ||  ';' FROM I_PRODUCT_GROUP_MEMBERS;

prompt DROP SEQUENCE  I_SUPPLIERS_SEQ;;
SELECT 'CREATE SEQUENCE I_SUPPLIERS_SEQ INCREMENT BY 1 START WITH '|| DECODE(MAX(F_RECORD_KEY)+1, NULL, 1, MAX(F_RECORD_KEY)+1) ||  ';' FROM I_SUPPLIERS;

prompt COMMIT;;

prompt SPOOL OFF;;

SPOOL OFF;


SET LINESIZE 80
SET PAGESIZE 24
SET TERMOUT ON
SET FEEDBACK ON
