SPOOL C:\ORATEMP\Graphics61Updt.log


/*

C://WERCS/

C:/WERCS/
C:\WERCS\
P:\WERCS\

C:\DYKES\BACKUPDATA\SYMBOLS\

C:\MY DOCUMENTS\CUSTOMERS\FERRO\

C:\PROGRAM FILES\WERCS50\GRAPHICS\
D:/PROGRAM FILES/WERCS50/GRAPHICS/
D:\PROGRAM FILES\WERCS50\GRAPHICS\
P:\PROGRAM FILES\WERCS50\GRAPHICS\
W:\PROGRAM FILES\WERCS50\GRAPHICS\

G:\GRAPHICS\
H:\GRAPHICS\


*/


--Graphic Paths

UPDATE T_TEXT_DETAILS SET F_TEXT_LINE = REPLACE(TRIM(substr(f_text_line,10)),'\','/')
WHERE UPPER(F_TEXT_LINE) like 'C:/WERCS/%';

UPDATE T_TEXT_DETAILS SET F_TEXT_LINE = REPLACE(TRIM(substr(f_text_line,10)),'\','/')
WHERE UPPER(F_TEXT_LINE) like 'C:\WERCS\%';

UPDATE T_TEXT_DETAILS SET F_TEXT_LINE = REPLACE(TRIM(substr(f_text_line,10)),'\','/')
WHERE UPPER(F_TEXT_LINE) like 'P:\WERCS\%';

UPDATE T_TEXT_DETAILS SET F_TEXT_LINE = REPLACE(TRIM(substr(f_text_line,11)),'\','/')
WHERE UPPER(F_TEXT_LINE) like 'C://WERCS/%';


UPDATE T_TEXT_DETAILS SET F_TEXT_LINE = REPLACE(TRIM(substr(f_text_line,35)),'\','/')
WHERE UPPER(F_TEXT_LINE) like 'C:\PROGRAM FILES\WERCS50\GRAPHICS\%';

UPDATE T_TEXT_DETAILS SET F_TEXT_LINE = REPLACE(TRIM(substr(f_text_line,35)),'\','/')
WHERE UPPER(F_TEXT_LINE) like 'D:/PROGRAM FILES/WERCS50/GRAPHICS/%';

UPDATE T_TEXT_DETAILS SET F_TEXT_LINE = REPLACE(TRIM(substr(f_text_line,35)),'\','/')
WHERE UPPER(F_TEXT_LINE) like 'D:\PROGRAM FILES\WERCS50\GRAPHICS\%';

UPDATE T_TEXT_DETAILS SET F_TEXT_LINE = REPLACE(TRIM(substr(f_text_line,35)),'\','/')
WHERE UPPER(F_TEXT_LINE) like 'P:\PROGRAM FILES\WERCS50\GRAPHICS\%';

UPDATE T_TEXT_DETAILS SET F_TEXT_LINE = REPLACE(TRIM(substr(f_text_line,35)),'\','/')
WHERE UPPER(F_TEXT_LINE) like 'W:\PROGRAM FILES\WERCS50\GRAPHICS\%';


UPDATE T_TEXT_DETAILS SET F_TEXT_LINE = REPLACE(TRIM(substr(f_text_line,29)),'\','/')
WHERE UPPER(F_TEXT_LINE) like 'C:\DYKES\BACKUPDATA\SYMBOLS\%';


UPDATE T_TEXT_DETAILS SET F_TEXT_LINE = REPLACE(TRIM(substr(f_text_line,33)),'\','/')
WHERE UPPER(F_TEXT_LINE) like 'C:\MY DOCUMENTS\CUSTOMERS\FERRO\%';


UPDATE T_TEXT_DETAILS SET F_TEXT_LINE = REPLACE(TRIM(substr(f_text_line,13)),'\','/')
WHERE UPPER(F_TEXT_LINE) like 'G:\GRAPHICS\%';

UPDATE T_TEXT_DETAILS SET F_TEXT_LINE = REPLACE(TRIM(substr(f_text_line,13)),'\','/')
WHERE UPPER(F_TEXT_LINE) like 'H:\GRAPHICS\%';





UPDATE T_PROD_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,10)),'\','/')
WHERE UPPER(F_DATA) like 'C:/WERCS/%';

UPDATE T_PROD_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,10)),'\','/')
WHERE UPPER(F_DATA) like 'C:\WERCS\%';

UPDATE T_PROD_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,10)),'\','/')
WHERE UPPER(F_DATA) like 'P:\WERCS\%';

UPDATE T_PROD_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,11)),'\','/')
WHERE UPPER(F_DATA) like 'C://WERCS/%';


UPDATE T_PROD_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,35)),'\','/')
WHERE UPPER(F_DATA) like 'C:\PROGRAM FILES\WERCS50\GRAPHICS\%';

UPDATE T_PROD_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,35)),'\','/')
WHERE UPPER(F_DATA) like 'D:/PROGRAM FILES/WERCS50/GRAPHICS/%';

UPDATE T_PROD_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,35)),'\','/')
WHERE UPPER(F_DATA) like 'D:\PROGRAM FILES\WERCS50\GRAPHICS\%';

UPDATE T_PROD_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,35)),'\','/')
WHERE UPPER(F_DATA) like 'P:\PROGRAM FILES\WERCS50\GRAPHICS\%';

UPDATE T_PROD_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,35)),'\','/')
WHERE UPPER(F_DATA) like 'W:\PROGRAM FILES\WERCS50\GRAPHICS\%';


UPDATE T_PROD_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,29)),'\','/')
WHERE UPPER(F_DATA) like 'C:\DYKES\BACKUPDATA\SYMBOLS\%';


UPDATE T_PROD_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,33)),'\','/')
WHERE UPPER(F_DATA) like 'C:\MY DOCUMENTS\CUSTOMERS\FERRO\%';


UPDATE T_PROD_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,13)),'\','/')
WHERE UPPER(F_DATA) like 'G:\GRAPHICS\%';

UPDATE T_PROD_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,13)),'\','/')
WHERE UPPER(F_DATA) like 'H:\GRAPHICS\%';




UPDATE T_COMP_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,10)),'\','/')
WHERE UPPER(F_DATA) like 'C:/WERCS/%';

UPDATE T_COMP_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,10)),'\','/')
WHERE UPPER(F_DATA) like 'C:\WERCS\%';

UPDATE T_COMP_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,10)),'\','/')
WHERE UPPER(F_DATA) like 'P:\WERCS\%';

UPDATE T_COMP_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,11)),'\','/')
WHERE UPPER(F_DATA) like 'C://WERCS/%';


UPDATE T_COMP_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,35)),'\','/')
WHERE UPPER(F_DATA) like 'C:\PROGRAM FILES\WERCS50\GRAPHICS\%';

UPDATE T_COMP_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,35)),'\','/')
WHERE UPPER(F_DATA) like 'D:/PROGRAM FILES/WERCS50/GRAPHICS/%';

UPDATE T_COMP_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,35)),'\','/')
WHERE UPPER(F_DATA) like 'D:\PROGRAM FILES\WERCS50\GRAPHICS\%';

UPDATE T_COMP_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,35)),'\','/')
WHERE UPPER(F_DATA) like 'P:\PROGRAM FILES\WERCS50\GRAPHICS\%';

UPDATE T_COMP_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,35)),'\','/')
WHERE UPPER(F_DATA) like 'W:\PROGRAM FILES\WERCS50\GRAPHICS\%';


UPDATE T_COMP_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,29)),'\','/')
WHERE UPPER(F_DATA) like 'C:\DYKES\BACKUPDATA\SYMBOLS\%';


UPDATE T_COMP_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,33)),'\','/')
WHERE UPPER(F_DATA) like 'C:\MY DOCUMENTS\CUSTOMERS\FERRO\%';


UPDATE T_COMP_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,13)),'\','/')
WHERE UPPER(F_DATA) like 'G:\GRAPHICS\%';

UPDATE T_COMP_DATA SET F_DATA = REPLACE(TRIM(substr(F_DATA,13)),'\','/')
WHERE UPPER(F_DATA) like 'H:\GRAPHICS\%';





UPDATE T_B_RULES SET F_FILE_STRING_FOR_SYMBOL_FROM = REPLACE(TRIM(substr(F_FILE_STRING_FOR_SYMBOL_FROM,35)),'\','/')
WHERE UPPER(F_FILE_STRING_FOR_SYMBOL_FROM) like 'C:\PROGRAM FILES\WERCS50\GRAPHICS\%';

UPDATE T_B_RULES SET F_FILE_STRING_FOR_SYMBOL_TO = REPLACE(TRIM(substr(F_FILE_STRING_FOR_SYMBOL_TO,35)),'\','/')
WHERE UPPER(F_FILE_STRING_FOR_SYMBOL_TO) like 'C:\PROGRAM FILES\WERCS50\GRAPHICS\%';



COMMIT;


--Defaults

UPDATE t_datatypes 
SET t_datatypes.F_Default_Code=(SELECT F_Text_Line FROM T_TEXT_DETAILS WHERE t_datatypes.f_data_code = t_text_details.f_prefix 
	and t_datatypes.F_Default_Code = T_TEXT_DETAILS.F_Text_Code AND T_TEXT_DETAILS.F_Language='EN') 
WHERE t_datatypes.F_Database_Origin_Code='GRPH'
and t_datatypes.f_default_code is not null
and length(trim(t_datatypes.f_default_code)) > 0;



COMMIT;


--Plus Graphics

UPDATE T_B_RULES
SET F_FILE_STRING_FOR_SYMBOL_FROM = TRIM(REPLACE(F_FILE_STRING_FOR_SYMBOL_FROM, '+.','plus.')),
F_DESC = REPLACE(F_DESC, '+.','plus.')
WHERE F_FILE_STRING_FOR_SYMBOL_FROM like '%+.%';

UPDATE T_B_RULES
SET F_FILE_STRING_FOR_SYMBOL_TO = TRIM(REPLACE(F_FILE_STRING_FOR_SYMBOL_TO, '+.','plus.')),
F_DESC = REPLACE(F_DESC, '+.','plus.')
WHERE F_FILE_STRING_FOR_SYMBOL_TO like '%+.%';

UPDATE T_B_RULES_EXT
SET F_FILE_STRING_FOR_SYMBOL_FROM = TRIM(REPLACE(F_FILE_STRING_FOR_SYMBOL_FROM, '+.','plus.')),
F_DESC = REPLACE(F_DESC, '+.','plus.')
WHERE F_FILE_STRING_FOR_SYMBOL_FROM like '%+.%';


UPDATE T_E_RULES
SET F_SYMBOL_TO = TRIM(REPLACE(F_SYMBOL_TO, '+.','plus.')),
F_DESC = REPLACE(F_DESC, '+.','plus.')
WHERE F_SYMBOL_TO like '%+.%';

UPDATE T_F_RULES
SET F_SYMBOL_TO = TRIM(REPLACE(F_SYMBOL_TO, '+.','plus.')),
F_DESC = REPLACE(F_DESC, '+.','plus.')
WHERE F_SYMBOL_TO like '%+.%';





UPDATE T_PROD_DATA
SET F_DATA = TRIM(REPLACE(F_DATA, '+.','plus.'))
WHERE F_DATA like '%+.%'
AND EXISTS (SELECT 'X' FROM T_DATATYPES B
WHERE B.F_DATA_CODE = T_PROD_DATA.F_DATA_CODE
AND B.F_DATABASE_ORIGIN_CODE = 'GRPH');



UPDATE T_COMP_DATA
SET F_DATA = TRIM(REPLACE(F_DATA, '+.','plus.'))
WHERE F_DATA like '%+.%'
AND EXISTS (SELECT 'X' FROM T_DATATYPES B
WHERE B.F_DATA_CODE = T_COMP_DATA.F_DATA_CODE
AND B.F_DATABASE_ORIGIN_CODE = 'GRPH');


COMMIT;


SPOOL OFF;


