SPOOL c:\oratemp\IntSeq.log
DROP SEQUENCE  I_ALIASES_SEQ;
CREATE SEQUENCE I_ALIASES_SEQ INCREMENT BY 1 START WITH 478992;
DROP SEQUENCE  I_ATTRIBUTES_SEQ;
CREATE SEQUENCE I_ATTRIBUTES_SEQ INCREMENT BY 1 START WITH 5909884;
DROP SEQUENCE  I_COMPONENTS_SEQ;
CREATE SEQUENCE I_COMPONENTS_SEQ INCREMENT BY 1 START WITH 183649;
DROP SEQUENCE  I_DOCUMENTS_SEQ;
CREATE SEQUENCE I_DOCUMENTS_SEQ INCREMENT BY 1 START WITH 1;
DROP SEQUENCE  I_ETLLOG_SEQ;
CREATE SEQUENCE I_ETLLOG_SEQ INCREMENT BY 1 START WITH 1;
DROP SEQUENCE  I_FORMULATIONS_SEQ;
CREATE SEQUENCE I_FORMULATIONS_SEQ INCREMENT BY 1 START WITH 5152373;
DROP SEQUENCE  I_LABELS_SEQ;
CREATE SEQUENCE I_LABELS_SEQ INCREMENT BY 1 START WITH 1;
DROP SEQUENCE  I_LABEL_DETAILS_SEQ;
CREATE SEQUENCE I_LABEL_DETAILS_SEQ INCREMENT BY 1 START WITH 1;
DROP SEQUENCE  I_LABEL_PRINTERS_SEQ;
CREATE SEQUENCE I_LABEL_PRINTERS_SEQ INCREMENT BY 1 START WITH 1;
DROP SEQUENCE  I_LOLI_LOAD_SEQ;
CREATE SEQUENCE I_LOLI_LOAD_SEQ INCREMENT BY 1 START WITH 32307;
DROP SEQUENCE  I_ORDERS_SEQ;
SELECT 'CREATE SEQUENCE I_ORDERS_SEQ INCREMENT BY 1 START WITH '|| DECODE(MAX(F_RECORD_KEY)+1, NULL, 1, MAX(F_RECORD_KEY)+1) ||  ';' FROM I_ORDERS
                                                                                                                                          *
ERROR at line 1:
ORA-00942: table or view does not exist


DROP SEQUENCE  I_PHRASES_SEQ;
CREATE SEQUENCE I_PHRASES_SEQ INCREMENT BY 1 START WITH 1764;
DROP SEQUENCE  I_PROCESS_SEQ;
CREATE SEQUENCE I_PROCESS_SEQ INCREMENT BY 1 START WITH 616715;
DROP SEQUENCE  I_PROCESSES_SEQ;
CREATE SEQUENCE I_PROCESSES_SEQ INCREMENT BY 1 START WITH 530;
DROP SEQUENCE  I_PROCESS_GROUPS_SEQ;
CREATE SEQUENCE I_PROCESS_GROUPS_SEQ INCREMENT BY 1 START WITH 249;
DROP SEQUENCE  I_PROCESS_GROUP_MEMBERS_SEQ;
CREATE SEQUENCE I_PROCESS_GROUP_MEMBERS_SEQ INCREMENT BY 1 START WITH 1219;
DROP SEQUENCE  I_PRODUCTS_SEQ;
CREATE SEQUENCE I_PRODUCTS_SEQ INCREMENT BY 1 START WITH 350293;
DROP SEQUENCE  I_PRODUCT_GROUPS_SEQ;
CREATE SEQUENCE I_PRODUCT_GROUPS_SEQ INCREMENT BY 1 START WITH 43;
DROP SEQUENCE  I_PRODUCT_GROUP_MEMBERS_SEQ;
CREATE SEQUENCE I_PRODUCT_GROUP_MEMBERS_SEQ INCREMENT BY 1 START WITH 44;
DROP SEQUENCE  I_SUPPLIERS_SEQ;
CREATE SEQUENCE I_SUPPLIERS_SEQ INCREMENT BY 1 START WITH 1;
COMMIT;
SPOOL OFF;
