REM----------------------------------------------------------------------------
REM	Builds a script that SELECT 'CREATEs and Initializes all WERCS 5.x Sequences
REM
REM	Author - Steve Giamalis  12/03/2002
REM
REM	Changes
REM	-----------------------------------------------------------------------
REM	
REM	
REM
REM----------------------------------------------------------------------------

SET TERMOUT OFF
SET PAGESIZE 0
SET TRIMSPOOL ON
SET LINESIZE 100
SET FEEDBACK OFF


SET HEAD OFF;
SPOOL c:\oratemp\seq6X.sql

prompt SPOOL c:\oratemp\seq6X.log;


prompt DROP SEQUENCE  C_REACH01_SEQ;;
SELECT 'CREATE SEQUENCE  C_REACH01_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_RECORD_ID)+1, NULL, 1, MAX(F_RECORD_ID)+1) || ';' FROM C_REACH01;

prompt DROP SEQUENCE  C_REACH02_SEQ;;
SELECT 'CREATE SEQUENCE  C_REACH02_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_RECORD_ID)+1, NULL, 1, MAX(F_RECORD_ID)+1) || ';' FROM C_REACH02;



prompt DROP SEQUENCE  CASINDEX_SEQ;;
SELECT 'CREATE SEQUENCE  CASINDEX_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(RECORDID)+1, NULL, 1, MAX(RECORDID)+1) || ';' FROM CASINDEX;





prompt DROP SEQUENCE T_APP_OBJECTS_SEQ;;
SELECT 'CREATE SEQUENCE T_APP_OBJECTS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_OBJECT_ID)+1, NULL, 1, MAX(F_OBJECT_ID)+1) || ';' FROM T_APP_OBJECTS;

prompt DROP SEQUENCE T_ARIEL_REGS_SEQ;;
SELECT 'CREATE SEQUENCE T_ARIEL_REGS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_RECORD_ID)+1, NULL, 1, MAX(F_RECORD_ID)+1) || ';' FROM T_ARIEL_REGS;

prompt DROP SEQUENCE T_B_RULES_EXT_SEQ;;
SELECT 'CREATE SEQUENCE  T_B_RULES_EXT_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_EXT_NUMBER)+1, NULL, 1, MAX(F_EXT_NUMBER)+1) || ';' FROM T_B_RULES_EXT;

prompt DROP SEQUENCE  T_BATCH_JOBS_SEQ;;
SELECT 'CREATE SEQUENCE  T_BATCH_JOBS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_COUNTER)+1, NULL, 1, MAX(F_COUNTER)+1) || ';' FROM T_BATCH_JOBS;

prompt DROP SEQUENCE  T_CALC_TASKS_SEQ;;
SELECT 'CREATE SEQUENCE  T_CALC_TASKS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_ID)+1, NULL, 1, MAX(F_ID)+1) || ';' FROM T_CALC_TASKS;


prompt DROP SEQUENCE  T_COMP_TEXT_SEQ;;
SELECT 'CREATE SEQUENCE  T_COMP_TEXT_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_COUNTER)+1, NULL, 1, MAX(F_COUNTER)+1) || ';' FROM T_COMP_TEXT;


prompt DROP SEQUENCE  T_CONTACTS_SEQ;;
SELECT 'CREATE SEQUENCE  T_CONTACTS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_CONTACT_ID)+1, NULL, 1, MAX(F_CONTACT_ID)+1) || ';' FROM T_CONTACTS;





prompt DROP SEQUENCE  T_CUST_ORD_SEQ;;
SELECT 'CREATE SEQUENCE  T_CUST_ORD_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_ORDER_ID)+1, NULL, 1, MAX(F_ORDER_ID)+1) || ';' FROM T_CUSTOMER_ORDERS;

prompt DROP SEQUENCE  T_DATATYPES_SEQ;;
SELECT 'CREATE SEQUENCE  T_DATATYPES_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_COUNTER)+1, NULL, 1, MAX(F_COUNTER)+1) || ';' FROM T_DATATYPES;


prompt DROP SEQUENCE  T_DOCUMENTS_SEQ;;
SELECT 'CREATE SEQUENCE  T_DOCUMENTS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_RECORD_ID)+1, NULL, 1, MAX(F_RECORD_ID)+1) || ';' FROM T_DOCUMENTS;

prompt DROP SEQUENCE  T_DOCUMENT_QUEUE_SEQ;;
SELECT 'CREATE SEQUENCE  T_DOCUMENT_QUEUE_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_RECORDID)+1, NULL, 1, MAX(F_RECORDID)+1) || ';' FROM T_DOCUMENT_QUEUE;

prompt DROP SEQUENCE  T_DOC_ARCHIVE_SEQ;;
SELECT 'CREATE SEQUENCE  T_DOC_ARCHIVE_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_RECORD_ID)+1, NULL, 1, MAX(F_RECORD_ID)+1) || ';' FROM T_DOC_ARCHIVE;

prompt DROP SEQUENCE  T_DOC_DOM_SEQ;;
SELECT 'CREATE SEQUENCE  T_DOC_DOM_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_DOC_DOM)+1, NULL, 1, MAX(F_DOC_DOM)+1) || ';' FROM T_DOC_DOM;

prompt DROP SEQUENCE  T_DOC_FULL_TEXT_SEQ;;
SELECT 'CREATE SEQUENCE  T_DOC_FULL_TEXT_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_DOC_FULL_TEXT_ID)+1, NULL, 1, MAX(F_DOC_FULL_TEXT_ID)+1) || ';' FROM T_DOC_FULL_TEXT;


prompt DROP SEQUENCE  T_DW_FILES_SEQ;;
SELECT 'CREATE SEQUENCE  T_DW_FILES_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_RECORD_ID)+1, NULL, 1, MAX(F_RECORD_ID)+1) || ';' FROM T_DW_FILES;


prompt DROP SEQUENCE  T_EMAIL_ATTACHMENT_SEQ;;
SELECT 'CREATE SEQUENCE  T_EMAIL_ATTACHMENT_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_ATTACHMENT_ID)+1, NULL, 1, MAX(F_ATTACHMENT_ID)+1) || ';' FROM T_EMAIL_ATTACHMENT;

prompt DROP SEQUENCE  T_EMAIL_DATA_SEQ;;
SELECT 'CREATE SEQUENCE  T_EMAIL_DATA_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_RECORDID)+1, NULL, 1, MAX(F_RECORDID)+1) || ';' FROM T_EMAIL_DATA;


prompt DROP SEQUENCE  T_EMAIL_JOB_DATA_SEQ;;
SELECT 'CREATE SEQUENCE  T_EMAIL_JOB_DATA_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_RECORDID)+1, NULL, 1, MAX(F_RECORDID)+1) || ';' FROM T_EMAIL_JOB_DATA;


prompt DROP SEQUENCE  T_EXT_NAMES_SEQ;;
SELECT 'CREATE SEQUENCE  T_EXT_NAMES_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_COUNTER)+1, NULL, 1, MAX(F_COUNTER)+1) || ';' FROM T_EXT_NAMES;

prompt DROP SEQUENCE  T_FORM_TEXT_SEQ;;
SELECT 'CREATE SEQUENCE  T_FORM_TEXT_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_COUNTER)+1, NULL, 1, MAX(F_COUNTER)+1) || ';' FROM T_FORM_TEXT;

prompt DROP SEQUENCE  T_GENERIC_AUDIT_TRAIL_SEQ;;
SELECT 'CREATE SEQUENCE  T_GENERIC_AUDIT_TRAIL_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_COUNTER)+1, NULL, 1, MAX(F_COUNTER)+1) || ';' FROM T_GENERIC_AUDIT_TRAIL;



prompt DROP SEQUENCE  T_GHS_ENTITIES_SEQ;;
SELECT 'CREATE SEQUENCE  T_GHS_ENTITIES_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(ID)+1, NULL, 1, MAX(ID)+1) || ';' FROM T_GHS_ENTITIES;

prompt DROP SEQUENCE  T_GHS_PROJECTS_SEQ ;;
SELECT 'CREATE SEQUENCE  T_GHS_PROJECTS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_ID)+1, NULL, 1, MAX(F_ID)+1) || ';' FROM T_GHS_PROJECTS;




prompt DROP SEQUENCE  T_GW_CATEGORIES_SEQ;;
SELECT 'CREATE SEQUENCE  T_GW_CATEGORIES_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_CATEGORY_ID)+1, NULL, 1, MAX(F_CATEGORY_ID)+1) || ';' FROM T_GW_CATEGORIES;

prompt DROP SEQUENCE  T_GW_MEMBERS_SEQ;;
SELECT 'CREATE SEQUENCE  T_GW_MEMBERS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_MEMBER_ID)+1, NULL, 1, MAX(F_MEMBER_ID)+1) || ';' FROM T_GW_MEMBERS;

prompt DROP SEQUENCE  T_GW_REG_VIEWS_SEQ;;
SELECT 'CREATE SEQUENCE  T_GW_REG_VIEWS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_VIEW_ID)+1, NULL, 1, MAX(F_VIEW_ID)+1) || ';' FROM T_GW_REG_VIEWS;



prompt DROP SEQUENCE  T_INPUT_PROD_TEXT_SEQ;;
SELECT 'CREATE SEQUENCE  T_INPUT_PROD_TEXT_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_COUNTER)+1, NULL, 1, MAX(F_COUNTER)+1) || ';' FROM T_INPUT_PROD_TEXT;

prompt DROP SEQUENCE  T_IUCLID4_WERCS_XREF_SEQ;;
SELECT 'CREATE SEQUENCE  T_IUCLID4_WERCS_XREF_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_RECORD_ID)+1, NULL, 1, MAX(F_RECORD_ID)+1) || ';' FROM T_IUCLID4_WERCS_XREF;

prompt DROP SEQUENCE  T_IUCLID_PHRASE_MAPPINGS_SEQ;;
SELECT 'CREATE SEQUENCE  T_IUCLID_PHRASE_MAPPINGS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_ID)+1, NULL, 1, MAX(F_ID)+1) || ';' FROM T_IUCLID_PHRASE_MAPPINGS;

prompt DROP SEQUENCE  T_IUCLID_SUBSTANCES_SEQ;;
SELECT 'CREATE SEQUENCE  T_IUCLID_SUBSTANCES_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_ID)+1, NULL, 1, MAX(F_ID)+1) || ';' FROM T_IUCLID_SUBSTANCES;





prompt DROP SEQUENCE  T_JOBS_SEQ;;
SELECT 'CREATE SEQUENCE  T_JOBS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_RECORD_ID)+1, NULL, 1, MAX(F_RECORD_ID)+1) || ';' FROM T_JOBS;



prompt DROP SEQUENCE T_LABEL_HIST_SEQ;;
SELECT 'CREATE SEQUENCE  T_LABEL_HIST_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(ID)+1, NULL, 1, MAX(ID)+1) || ';' FROM T_LABEL_HISTORY;


prompt DROP SEQUENCE  T_LOGS_SEQ;;
SELECT 'CREATE SEQUENCE  T_LOGS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_RECORD_ID)+1, NULL, 1, MAX(F_RECORD_ID)+1) || ';' FROM T_LOGS;



prompt DROP SEQUENCE  T_LOOKUP_TEXT_SEQ;;
SELECT 'CREATE SEQUENCE  T_LOOKUP_TEXT_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_COUNTER)+1, NULL, 1, MAX(F_COUNTER)+1) || ';' FROM T_LOOKUP_TEXT;




prompt DROP SEQUENCE T_MASS_MAIL_SEQ;;
SELECT 'CREATE SEQUENCE T_MASS_MAIL_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_COUNTER)+1, NULL, 1, MAX(F_COUNTER)+1) || ';' FROM T_MASS_MAIL;



prompt DROP SEQUENCE  T_MESSAGES_SEQ;;
SELECT 'CREATE SEQUENCE  T_MESSAGES_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_MESSAGE_ID)+1, NULL, 1, MAX(F_MESSAGE_ID)+1) || ';' FROM T_MESSAGES;

prompt DROP SEQUENCE  T_MESSAGE_HISTORY_SEQ;;
SELECT 'CREATE SEQUENCE  T_MESSAGE_HISTORY_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_RECORD_ID)+1, NULL, 1, MAX(F_RECORD_ID)+1) || ';' FROM T_MESSAGE_HISTORY;

prompt DROP SEQUENCE  T_MESSAGE_TYPES_SEQ;;
SELECT 'CREATE SEQUENCE  T_MESSAGE_TYPES_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_MESSAGE_TYPE_ID)+1, NULL, 1, MAX(F_MESSAGE_TYPE_ID)+1) || ';' FROM T_MESSAGE_TYPES;

prompt DROP SEQUENCE  T_MSDSTYPE_SECTIONS_SEQ;;
SELECT 'CREATE SEQUENCE  T_MSDSTYPE_SECTIONS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_COUNTER)+1, NULL, 1, MAX(F_COUNTER)+1) || ';' FROM T_MSDSTYPE_SECTIONS; 

prompt DROP SEQUENCE  T_PHRASES_SEQ;;
SELECT 'CREATE SEQUENCE  T_PHRASES_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_PHRASE_ID)+1, NULL, 1, MAX(F_PHRASE_ID)+1) || ';' FROM T_PHRASES; 

prompt DROP SEQUENCE  T_PHRASE_LINKAGE_SEQ;;
SELECT 'CREATE SEQUENCE  T_PHRASE_LINKAGE_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_LINK_ID)+1, NULL, 1, MAX(F_LINK_ID)+1) || ';' FROM T_PHRASE_LINKAGE; 

prompt DROP SEQUENCE  T_PHRASE_TRANSLATIONS_SEQ;;
SELECT 'CREATE SEQUENCE  T_PHRASE_TRANSLATIONS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_TRANSLATION_ID)+1, NULL, 1, MAX(F_TRANSLATION_ID)+1) || ';' FROM T_PHRASE_TRANSLATIONS; 

prompt DROP SEQUENCE  T_PRODUCT_ARCHIVE_SEQ;;
SELECT 'CREATE SEQUENCE  T_PRODUCT_ARCHIVE_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_RECORDID)+1, NULL, 1, MAX(F_RECORDID)+1) || ';' FROM T_PRODUCT_ARCHIVE;

prompt DROP SEQUENCE  T_PROD_312_SEQ;;
SELECT 'CREATE SEQUENCE  T_PROD_312_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_PRIMARY_KEY)+1, NULL, 1, MAX(F_PRIMARY_KEY)+1) || ';' FROM T_SARA_PRODUCTS_FOR_SARA312;

prompt DROP SEQUENCE  T_PROD_ALIAS_TEXT_SEQ;;
SELECT 'CREATE SEQUENCE  T_PROD_ALIAS_TEXT_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_COUNTER)+1, NULL, 1, MAX(F_COUNTER)+1) || ';' FROM T_PROD_ALIAS_TEXT;

prompt DROP SEQUENCE  T_PROD_TEXT_SEQ;;
SELECT 'CREATE SEQUENCE  T_PROD_TEXT_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_COUNTER)+1, NULL, 1, MAX(F_COUNTER)+1) || ';' FROM T_PROD_TEXT;

prompt DROP SEQUENCE  T_REACH_FUNCTIONS_SEQ;;
SELECT 'CREATE SEQUENCE  T_REACH_FUNCTIONS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_RECORD_ID)+1, NULL, 1, MAX(F_RECORD_ID)+1) || ';' FROM T_REACH_FUNCTIONS;

prompt DROP SEQUENCE  T_REACH_LEOS_SEQ;;
SELECT 'CREATE SEQUENCE  T_REACH_LEOS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_RECORD_ID)+1, NULL, 1, MAX(F_RECORD_ID)+1) || ';' FROM T_REACH_LEOS;

prompt DROP SEQUENCE  T_REACH_VOLUMES_SEQ;;
SELECT 'CREATE SEQUENCE  T_REACH_VOLUMES_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_RECORD_ID)+1, NULL, 1, MAX(F_RECORD_ID)+1) || ';' FROM T_REACH_VOLUMES;

prompt DROP SEQUENCE  T_REPORTS_SEQ;;
SELECT 'CREATE SEQUENCE  T_REPORTS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_RECORD_ID)+1, NULL, 1, MAX(F_RECORD_ID)+1) || ';' FROM T_REPORTS;

prompt DROP SEQUENCE  T_REPORT_DEFINITIONS_SEQ;;
SELECT 'CREATE SEQUENCE  T_REPORT_DEFINITIONS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_RECORD_ID)+1, NULL, 1, MAX(F_RECORD_ID)+1) || ';' FROM T_REPORT_DEFINITIONS;

prompt DROP SEQUENCE  T_REP_COMP_DATASETS_SEQ;;
SELECT 'CREATE SEQUENCE  T_REP_COMP_DATASETS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_SEQUENCE)+1, NULL, 1, MAX(F_SEQUENCE)+1) || ';' FROM T_REP_COMP_DATASETS;

prompt DROP SEQUENCE  T_REP_COMP_TEXT_SEQ;;
SELECT 'CREATE SEQUENCE  T_REP_COMP_TEXT_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_COUNTER)+1, NULL, 1, MAX(F_COUNTER)+1) || ';' FROM T_REP_COMP_TEXT;

prompt DROP SEQUENCE  T_REP_DATASETS_SEQ;;
SELECT 'CREATE SEQUENCE  T_REP_DATASETS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_DATASET)+1, NULL, 1, MAX(F_DATASET)+1) || ';' FROM T_REP_DATASETS;

prompt DROP SEQUENCE  T_REP_DATASET_MEMBERS_SEQ;;
SELECT 'CREATE SEQUENCE  T_REP_DATASET_MEMBERS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_COUNTER)+1, NULL, 1, MAX(F_COUNTER)+1) || ';' FROM T_REP_DATASET_MEMBERS;

prompt DROP SEQUENCE  T_REP_PROD_ALIAS_TEXT_SEQ;;
SELECT 'CREATE SEQUENCE  T_REP_PROD_ALIAS_TEXT_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_COUNTER)+1, NULL, 1, MAX(F_COUNTER)+1) || ';' FROM T_REP_PROD_ALIAS_TEXT;

prompt DROP SEQUENCE  T_REP_PROD_DATASETS_SEQ;;
SELECT 'CREATE SEQUENCE  T_REP_PROD_DATASETS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_SEQUENCE)+1, NULL, 1, MAX(F_SEQUENCE)+1) || ';' FROM T_REP_PROD_DATASETS;


prompt DROP SEQUENCE  T_RESERVED_DATACODE_CATS_SEQ;;
SELECT 'CREATE SEQUENCE  T_RESERVED_DATACODE_CATS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_ID)+1, NULL, 1, MAX(F_ID)+1) || ';' FROM T_RESERVED_DATACODE_CATEGORIES;


prompt DROP SEQUENCE  T_REV_REASONS_SEQ;;
SELECT 'CREATE SEQUENCE  T_REV_REASONS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_SEQUENCE)+1, NULL, 1, MAX(F_SEQUENCE)+1) || ';' FROM T_REV_REASONS;

prompt DROP SEQUENCE  T_RSS_ARTICLES_SEQ;;
SELECT 'CREATE SEQUENCE  T_RSS_ARTICLES_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_ARTICLEID)+1, NULL, 1, MAX(F_ARTICLEID)+1) || ';' FROM T_RSS_ARTICLES;

prompt DROP SEQUENCE  T_RSS_FEEDS_SEQ;;
SELECT 'CREATE SEQUENCE  T_RSS_FEEDS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_FEEDID)+1, NULL, 1, MAX(F_FEEDID)+1) || ';' FROM T_RSS_FEEDS;

prompt DROP SEQUENCE  T_RULES_SEQ;;
SELECT 'CREATE SEQUENCE  T_RULES_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_RULE_NUMBER)+1, NULL, 1, MAX(F_RULE_NUMBER)+1) || ';' FROM T_RULES;

prompt DROP SEQUENCE  T_RULE_GROUPS_SEQ;;
SELECT 'CREATE SEQUENCE  T_RULE_GROUPS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_GROUP_ID)+1, NULL, 1, MAX(F_GROUP_ID)+1) || ';' FROM T_RULE_GROUPS;

prompt DROP SEQUENCE  T_SARA_LOC_SEQ;;
SELECT 'CREATE SEQUENCE  T_SARA_LOC_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(RECID)+1, NULL, 1, MAX(RECID)+1) || ';' FROM T_SARA_STORAGE_LOCATION;

prompt DROP SEQUENCE  T_SUBFORMAT_LANGUAGES_SEQ;;
SELECT 'CREATE SEQUENCE  T_SUBFORMAT_LANGUAGES_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_RECORD_ID)+1, NULL, 1, MAX(F_RECORD_ID)+1) || ';' FROM T_SUBFORMAT_LANGUAGES;

prompt DROP SEQUENCE  T_TASKS_SEQ;;
SELECT 'CREATE SEQUENCE  T_TASKS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_TASK_ID)+1, NULL, 1, MAX(F_TASK_ID)+1) || ';' FROM T_TASKS;

prompt DROP SEQUENCE  T_TASK_GROUPS_SEQ;;
SELECT 'CREATE SEQUENCE  T_TASK_GROUPS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_GROUP_ID)+1, NULL, 1, MAX(F_GROUP_ID)+1) || ';' FROM T_TASK_GROUPS;

prompt DROP SEQUENCE  T_TASK_GROUPS_OBJECTS_SEQ;;
SELECT 'CREATE SEQUENCE  T_TASK_GROUPS_OBJECTS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_CHAIN)+1, NULL, 1, MAX(F_CHAIN)+1) || ';' FROM T_TASK_GROUPS_OBJECTS;

prompt DROP SEQUENCE  T_TASK_GROUP_MEMBERS_SEQ;;
SELECT 'CREATE SEQUENCE  T_TASK_GROUP_MEMBERS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_MEMBER_ID)+1, NULL, 1, MAX(F_MEMBER_ID)+1) || ';' FROM T_TASK_GROUP_MEMBERS;

prompt DROP SEQUENCE  T_TASK_STATUS_SEQ;;
SELECT 'CREATE SEQUENCE  T_TASK_STATUS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_COUNTER)+1, NULL, 1, MAX(F_COUNTER)+1) || ';' FROM T_TASK_STATUS;

prompt DROP SEQUENCE  T_TASK_STATUS_HIST_SEQ;;
SELECT 'CREATE SEQUENCE  T_TASK_STATUS_HIST_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_COUNTER)+1, NULL, 1, MAX(F_COUNTER)+1) || ';' FROM T_TASK_STATUS_HISTORY;


prompt DROP SEQUENCE  T_TLID_SEQ;;
SELECT 'CREATE SEQUENCE  T_TLID_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_TLID)+1, NULL, 1, MAX(F_TLID)+1) || ';' FROM T_TLID;



prompt DROP SEQUENCE  T_VOC_SEQ;;
SELECT 'CREATE SEQUENCE  T_VOC_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_RECORD_ID)+1, NULL, 1, MAX(F_RECORD_ID)+1) || ';' FROM T_VOC;

prompt DROP SEQUENCE  T_WERCS_METRICS_SEQ;;
SELECT 'CREATE SEQUENCE  T_WERCS_METRICS_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_RECORD_ID)+1, NULL, 1, MAX(F_RECORD_ID)+1) || ';' FROM T_WERCS_METRICS;



prompt DROP SEQUENCE  T_XML_BRIDGE_QUEUE_SEQ;;
SELECT 'CREATE SEQUENCE  T_XML_BRIDGE_QUEUE_SEQ INCREMENT BY 1 START WITH ' || 
DECODE(MAX(F_ID)+1, NULL, 1, MAX(F_ID)+1) || ';' FROM T_XML_BRIDGE_QUEUE;


prompt COMMIT;;

prompt SPOOL OFF;;

SPOOL OFF;


SET LINESIZE 80
SET PAGESIZE 24
SET TERMOUT ON
SET FEEDBACK ON
