DROP SEQUENCE  I_ORDERS_SEQ;
CREATE SEQUENCE  I_ORDERS_SEQ INCREMENT BY 1 START WITH 1;

CREATE TABLE WERCS.I_ORDERS (
  F_RECORD_KEY NUMBER (20,0),
  F_JOB_ID NVARCHAR2(30),
  F_PLANT NVARCHAR2(10) NULL,
  F_CUSTOMER_ID NVARCHAR2(50) NULL,
  F_ADDRESS_TYPE NVARCHAR2(10) NULL,
  F_CUSTOMER_TYPE NVARCHAR2(2) NULL,
  F_PRODUCT NVARCHAR2(50) NULL,
  F_CUSTOMER_NAME NVARCHAR2(35) NULL,
  F_ADDRESS1 NVARCHAR2(255) NULL,
  F_ADDRESS2 NVARCHAR2(255) NULL,
  F_CITY NVARCHAR2(50) NULL,
  F_STATE NVARCHAR2(25) NULL,
  F_ZIP_CODE NVARCHAR2(20) NULL,
  F_COUNTRY_CODE NVARCHAR2(3) NULL,
  F_ATTENTION_LINE NVARCHAR2(35) NULL,
  F_DESTINATION NVARCHAR2(255) NULL,
  F_NUM_COPIES NUMBER (5,0)NULL,
  F_DATE_REQUESTED DATE NULL,
  F_TIME_REQUESTED DATE NULL,
  F_ALWAYS_SEND NUMBER (2,0) NULL,
  F_SUBSTITUTIONS NVARCHAR2(255) NULL,
  F_CUST_ORDER NVARCHAR2(255) NULL,
  F_TELEPHONE NVARCHAR2(24) NULL,
  F_FAX NVARCHAR2(24) NULL,
  F_LANGUAGE NVARCHAR2(10) NULL,
  F_FORMAT NVARCHAR2(3) NULL,
  F_SUBFORMAT NVARCHAR2(4) NULL,
  F_QUANTITY NUMBER (10,2) NULL,
  F_UOM NVARCHAR2(50) NULL,
  F_CONT NVARCHAR2(50) NULL,
  F_STD_WGT NUMBER (10,2) NULL,
  F_CUSTOM1 NVARCHAR2(255) NULL,
  F_CUSTOM2 NVARCHAR2(255) NULL,
  F_CUSTOM3 NVARCHAR2(255) NULL,
  F_CUSTOM4 NVARCHAR2(255) NULL,
  F_CUSTOM5 NVARCHAR2(255) NULL,
  F_STATUS NUMBER(1,0),
  F_REMARKS NVARCHAR2(2000),
  F_USER_UPDATED NVARCHAR2(30),
  F_DATE_STAMP DATE,
  F_USER_INSERTED NVARCHAR2(30),
  F_DATE_STAMP_INSERTED DATE
)
   TABLESPACE WERCSDATA
   PCTFREE 10
   PCTUSED 50
   INITRANS 10
   MAXTRANS 255
 STORAGE ( 
   INITIAL 500K
   NEXT 500K
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS 300
   FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE;

ALTER TABLE I_ORDERS ADD 
 CONSTRAINT PK_I_ORDERS PRIMARY KEY 
(F_RECORD_KEY)
  USING INDEX 
  TABLESPACE WERCSIDX PCTFREE 10
  STORAGE(INITIAL 100K NEXT 100K PCTINCREASE 0 ) 
; 

CREATE OR REPLACE TRIGGER WERCS.I_ORDERS_TRIG BEFORE INSERT
ON WERCS.I_ORDERS
FOR EACH ROW
BEGIN
SELECT I_ORDERS_SEQ.NEXTVAL
INTO :NEW.F_RECORD_KEY
FROM DUAL;
END I_ORDERS_TRIG;
/

CREATE INDEX IDX_I_ORD_PROD
ON I_ORDERS
(F_PRODUCT)
  TABLESPACE WERCSIDX PCTFREE 40
  STORAGE(INITIAL 100K NEXT 100K PCTINCREASE 0 ) 
; 

CREATE INDEX IDX_I_ORD_CUST
ON I_ORDERS
(F_CUSTOMER_ID)
  TABLESPACE WERCSIDX PCTFREE 40
  STORAGE(INITIAL 100K NEXT 100K PCTINCREASE 0 ) 
; 

CREATE INDEX IDX_I_ORD_CUST_TYP
ON I_ORDERS
(F_CUSTOMER_TYPE)
  TABLESPACE WERCSIDX PCTFREE 40
  STORAGE(INITIAL 100K NEXT 100K PCTINCREASE 0 ) 
; 

CREATE INDEX IDX_I_ORD_ADD_TYP
ON I_ORDERS
(F_ADDRESS_TYPE)
  TABLESPACE WERCSIDX PCTFREE 40
  STORAGE(INITIAL 100K NEXT 100K PCTINCREASE 0 ) 
; 

CREATE INDEX IDX_I_ORD_COUNTRY
ON I_ORDERS
(F_COUNTRY_CODE)
  TABLESPACE WERCSIDX PCTFREE 40
  STORAGE(INITIAL 100K NEXT 100K PCTINCREASE 0 ) 
; 


CREATE INDEX IDX_I_ORD_PLANT
ON I_ORDERS
(F_PLANT)
  TABLESPACE WERCSIDX PCTFREE 40
  STORAGE(INITIAL 100K NEXT 100K PCTINCREASE 0 ) 
; 

CREATE INDEX IDX_I_ORD_FMT
ON I_ORDERS
(F_FORMAT)
  TABLESPACE WERCSIDX PCTFREE 40
  STORAGE(INITIAL 100K NEXT 100K PCTINCREASE 0 ) 
; 

CREATE INDEX IDX_I_ORD_SUBFMT
ON I_ORDERS
(F_SUBFORMAT)
  TABLESPACE WERCSIDX PCTFREE 40
  STORAGE(INITIAL 100K NEXT 100K PCTINCREASE 0 ) 
; 

CREATE INDEX IDX_I_ORD_FMT_SUBFMT
ON I_ORDERS
(F_FORMAT, F_SUBFORMAT)
  TABLESPACE WERCSIDX PCTFREE 40
  STORAGE(INITIAL 200K NEXT 200K PCTINCREASE 0 ) 
;

CREATE INDEX IDX_I_ORD_LANG
ON I_ORDERS
(F_LANGUAGE)
  TABLESPACE WERCSIDX PCTFREE 40
  STORAGE(INITIAL 100K NEXT 100K PCTINCREASE 0 ) 
; 

CREATE INDEX IDX_I_ORD_STAT
ON I_ORDERS
(F_STATUS)
  TABLESPACE WERCSIDX PCTFREE 40
  STORAGE(INITIAL 100K NEXT 100K PCTINCREASE 0 ) 
; 

CREATE INDEX IDX_I_ORD_JOBID
ON I_ORDERS
(F_JOB_ID)
  TABLESPACE WERCSIDX PCTFREE 40
  STORAGE(INITIAL 100K NEXT 100K PCTINCREASE 0 ) 
; 

CREATE INDEX IDX_I_ORD_JOB_STA
ON I_ORDERS
(F_JOB_ID, F_STATUS)
  TABLESPACE WERCSIDX PCTFREE 40
  STORAGE(INITIAL 100K NEXT 100K PCTINCREASE 0 ) 
; 

