SPOOL C:\ORATEMP\PhraseClean.log



DELETE T_TEXT_DETAILS WHERE TRIM(F_TEXT_KEY) = F_LANGUAGE;

UPDATE T_TEXT_DETAILS
SET F_PREFIX = F_TEXT_CODE
WHERE f_prefix is NULL 
and f_text_type = 'DT';

UPDATE T_TEXT_DETAILS
SET F_TEXT_KEY = UPPER(F_TEXT_KEY),
F_TEXT_CODE = UPPER(F_TEXT_CODE)
WHERE F_TEXT_CODE = 'DCTPc';

UPDATE T_TEXT_DETAILS
SET F_PREFIX = 'DCTPC'
WHERE F_PREFIX = 'DCTPc';


UPDATE T_TEXT_DETAILS
SET F_PREFIX = 'MTRLTR'
WHERE F_TEXT_CODE = 'MTRLTR01'
AND F_PREFIX IN ('EURLTR','USALTR');

DELETE T_TEXT_DETAILS
WHERE F_TEXT_KEY = F_LANGUAGE || 'forin396'
AND F_PREFIX = 'forin';

UPDATE T_TEXT_DETAILS
SET F_PREFIX = UPPER(F_PREFIX)
WHERE F_PREFIX = 'forin';

UPDATE T_TEXT_DETAILS
SET F_PREFIX = 'RISK'
WHERE F_PREFIX = 'TX'
AND F_TEXT_CODE = 'RISK0069';

UPDATE T_TEXT_DETAILS
SET F_PREFIX = '7.11',
F_TEXT_TYPE = 'DT'
WHERE F_PREFIX = '7.10'
AND F_TEXT_CODE = '7.11';

UPDATE T_TEXT_DETAILS
SET F_PREFIX = '1.51',
F_TEXT_TYPE = 'DT'
WHERE F_PREFIX = '1.50'
AND F_TEXT_CODE = '1.51';

UPDATE T_TEXT_DETAILS
SET F_PREFIX = '1.41',
F_TEXT_TYPE = 'DT'
WHERE F_PREFIX = '1.40'
AND F_TEXT_CODE = '1.41';




UPDATE T_TEXT_DETAILS
SET F_PREFIX = 'MTRLTR',
F_TEXT_CODE = 'MTRLTR01'
WHERE F_TEXT_KEY IN ('DAMTRLTR01','DEMTRLTR01','ELMTRLTR01','BDMTRLTR01','BEMTRLTR01','BFMTRLTR01','CFMTRLTR01','CSMTRLTR01')
AND F_PREFIX IN ('EURLTR','USALTR')
AND F_TEXT_CODE IN ('EURLTR01','USALTR01');

UPDATE T_TEXT_DETAILS
SET F_PREFIX = 'MTRLTR',
F_TEXT_CODE = 'MTRLTR02'
WHERE F_TEXT_KEY IN ('DAMTRLTR02','DEMTRLTR02','ELMTRLTR02')
AND F_PREFIX = 'USALTR'
AND F_TEXT_CODE = 'USALTR02';

UPDATE T_TEXT_DETAILS
SET F_PREFIX = 'MTRLTR',
F_TEXT_CODE = 'MTRLTR03'
WHERE F_TEXT_KEY IN ('DAMTRLTR03','DEMTRLTR03','ELMTRLTR03')
AND F_PREFIX = 'USALTR'
AND F_TEXT_CODE = 'USALTR03';

UPDATE T_TEXT_DETAILS
SET F_PREFIX = 'MTRLTR',
F_TEXT_CODE = 'MTRLTR04'
WHERE F_TEXT_KEY IN ('DAMTRLTR04','DEMTRLTR04','ELMTRLTR04')
AND F_PREFIX = 'USALTR'
AND F_TEXT_CODE = 'USALTR04';

UPDATE T_TEXT_DETAILS
SET F_PREFIX = 'MTRLTR',
F_TEXT_CODE = 'MTRLTR05'
WHERE F_TEXT_KEY IN ('DAMTRLTR05','DEMTRLTR05','ELMTRLTR05')
AND F_PREFIX = 'USALTR'
AND F_TEXT_CODE = 'USALTR05';

UPDATE T_TEXT_DETAILS
SET F_PREFIX = 'MTRLTR',
F_TEXT_CODE = 'MTRLTR06'
WHERE F_TEXT_KEY IN ('DAMTRLTR06','DEMTRLTR06','ELMTRLTR06')
AND F_PREFIX = 'USALTR'
AND F_TEXT_CODE = 'USALTR06';

UPDATE T_TEXT_DETAILS
SET F_PREFIX = 'MTRLTR',
F_TEXT_CODE = 'MTRLTR07'
WHERE F_TEXT_KEY IN ('DAMTRLTR07','DEMTRLTR07','ELMTRLTR07')
AND F_PREFIX = 'USALTR'
AND F_TEXT_CODE = 'USALTR07';

UPDATE T_TEXT_DETAILS
SET F_PREFIX = 'MTRLTR',
F_TEXT_CODE = 'MTRLTR08'
WHERE F_TEXT_KEY IN ('DAMTRLTR08','DEMTRLTR08','ELMTRLTR08')
AND F_PREFIX = 'USALTR'
AND F_TEXT_CODE = 'USALTR08';

UPDATE T_TEXT_DETAILS
SET F_PREFIX = 'MTRLTR',
F_TEXT_CODE = 'MTRLTR09'
WHERE F_TEXT_KEY IN ('DAMTRLTR09','DEMTRLTR09','ELMTRLTR09')
AND F_PREFIX = 'USALTR'
AND F_TEXT_CODE = 'USALTR09';






UPDATE T_TEXT_DETAILS
SET F_PREFIX = 'USALTR',
F_TEXT_CODE = 'USALTR01'
WHERE F_TEXT_KEY IN ('ATUSALTR01','BDUSALTR01','BEUSALTR01','BFUSALTR01', 'CFUSALTR01')
AND F_TEXT_CODE = 'MTRLTR01'
AND F_PREFIX = 'MTRLTR';

UPDATE T_TEXT_DETAILS
SET F_PREFIX = 'USALTR',
F_TEXT_CODE = 'USALTR02'
WHERE F_TEXT_KEY IN ('ATUSALTR02','BDUSALTR02','BEUSALTR02','BFUSALTR02')
AND F_TEXT_CODE = 'MTRLTR02'
AND F_PREFIX = 'MTRLTR';

UPDATE T_TEXT_DETAILS
SET F_PREFIX = 'USALTR',
F_TEXT_CODE = 'USALTR03'
WHERE F_TEXT_KEY IN ('ATUSALTR03','BDUSALTR03','BEUSALTR03','BFUSALTR03')
AND F_TEXT_CODE = 'MTRLTR03'
AND F_PREFIX = 'MTRLTR';

UPDATE T_TEXT_DETAILS
SET F_PREFIX = 'USALTR',
F_TEXT_CODE = 'USALTR04'
WHERE F_TEXT_KEY IN ('ATUSALTR04','BDUSALTR04','BEUSALTR04','BFUSALTR04')
AND F_TEXT_CODE = 'MTRLTR04'
AND F_PREFIX = 'MTRLTR';

UPDATE T_TEXT_DETAILS
SET F_PREFIX = 'USALTR',
F_TEXT_CODE = 'USALTR05'
WHERE F_TEXT_KEY IN ('ATUSALTR05','BDUSALTR05','BEUSALTR05','BFUSALTR05')
AND F_TEXT_CODE = 'MTRLTR05'
AND F_PREFIX = 'MTRLTR';

UPDATE T_TEXT_DETAILS
SET F_PREFIX = 'USALTR',
F_TEXT_CODE = 'USALTR06'
WHERE F_TEXT_KEY IN ('ATUSALTR06','BDUSALTR06','BEUSALTR06','BFUSALTR06')
AND F_TEXT_CODE = 'MTRLTR06'
AND F_PREFIX = 'MTRLTR';

UPDATE T_TEXT_DETAILS
SET F_PREFIX = 'USALTR',
F_TEXT_CODE = 'USALTR07'
WHERE F_TEXT_KEY IN ('ATUSALTR07','BDUSALTR07','BEUSALTR07','BFUSALTR07')
AND F_TEXT_CODE = 'MTRLTR07'
AND F_PREFIX = 'MTRLTR';

UPDATE T_TEXT_DETAILS
SET F_PREFIX = 'USALTR',
F_TEXT_CODE = 'USALTR08'
WHERE F_TEXT_KEY IN ('ATUSALTR08','BDUSALTR08','BEUSALTR08','BFUSALTR08')
AND F_TEXT_CODE = 'MTRLTR08'
AND F_PREFIX = 'MTRLTR';

UPDATE T_TEXT_DETAILS
SET F_PREFIX = 'USALTR',
F_TEXT_CODE = 'USALTR09'
WHERE F_TEXT_KEY IN ('ATUSALTR09','BDUSALTR09','BEUSALTR09','BFUSALTR09')
AND F_TEXT_CODE = 'MTRLTR09'
AND F_PREFIX = 'MTRLTR';



DELETE T_TEXT_DETAILS
WHERE F_LANGUAGE = 'DE'
AND F_PREFIX = 'ACTFEQ'
AND TRIM(F_TEXT_LINE) IS NULL;

DELETE T_TEXT_DETAILS
WHERE F_TEXT_KEY IN ('DEAFEQ0001','DEAFEQ0007','DEAFEQ0008');


UPDATE T_TEXT_DETAILS
SET F_TEXT_KEY = F_LANGUAGE || F_TEXT_CODE
WHERE F_TEXT_KEY LIKE F_LANGUAGE || 'AFEQ%'
AND F_PREFIX = 'ACTFEQ'
AND F_LANGUAGE = 'DE';


DELETE T_TEXT_DETAILS
WHERE F_TEXT_CODE = 'SECT111';

UPDATE T_TEXT_DETAILS
SET F_TEXT_TYPE = 'SE'
WHERE F_TEXT_CODE = 'SECT'
AND F_TEXT_TYPE = 'TX';

UPDATE T_TEXT_DETAILS
SET F_PREFIX = 'SECT'
WHERE F_TEXT_CODE LIKE 'SECT%'
AND F_PREFIX != 'SECT'
AND F_TEXT_TYPE = 'SE';




UPDATE T_TEXT_DETAILS
SET F_PREFIX = 'SECT', f_text_type = 'SE'
WHERE F_TEXT_CODE = 'SECT0913'
AND F_PREFIX = 'SECT0913';


UPDATE T_TEXT_DETAILS
SET F_PREFIX = '6.30'
WHERE F_TEXT_CODE = '6.300066'
AND F_PREFIX = F_TEXT_CODE;

UPDATE T_TEXT_DETAILS
SET F_PREFIX = 'GRAPHIC'
WHERE F_TEXT_CODE = 'GRAPHIC2'
AND F_PREFIX = F_TEXT_CODE;

UPDATE T_TEXT_DETAILS
SET F_TEXT_TYPE = 'DT'
WHERE f_text_code = f_prefix and f_text_type != 'DT'
and f_text_type != 'LB' AND F_TEXT_CODE != 'SECT';

DELETE T_TEXT_DETAILS
WHERE F_TEXT_KEY = 'PTSACT0001';



DELETE T_TEXT_DETAILS
WHERE F_LANGUAGE = 'PT'
AND F_PREFIX = 'ENGCNT'
AND F_TEXT_KEY LIKE 'PTPTGCNT%';

DELETE T_TEXT_DETAILS
WHERE F_TEXT_KEY = 'PTTRADPTM';


DELETE T_TEXT_DETAILS
WHERE F_TEXT_KEY = 'CNENGCNT01';

UPDATE T_TEXT_DETAILS
SET F_TEXT_KEY = 'CNENGCNT01'
WHERE F_TEXT_KEY = 'CNCNGCNT01';


DELETE T_TEXT_DETAILS
WHERE F_TEXT_KEY = 'CFDSL00020';

UPDATE T_TEXT_DETAILS
SET F_TEXT_KEY = 'CFDSL00020'
WHERE F_TEXT_KEY = 'CFDSL0020';


UPDATE T_TEXT_DETAILS
SET F_TEXT_CODE = 'CEF00000'
WHERE F_TEXT_KEY = 'ENCEF00000';


DELETE T_TEXT_DETAILS
WHERE F_TEXT_CODE = '14.68016'
AND F_TEXT_KEY = F_LANGUAGE || '14.69016';


DELETE T_TEXT_DETAILS
WHERE F_TEXT_CODE = 'RPHC0'
AND F_PREFIX = 'RPHC';



UPDATE T_TEXT_DETAILS
SET F_TEXT_KEY = F_LANGUAGE || 'ACTIN065',
F_TEXT_CODE = 'ACTIN065'
WHERE F_PREFIX = 'ACTIN'
AND F_TEXT_CODE = 'ACTIN60';


UPDATE T_TEXT_DETAILS
SET F_TEXT_KEY = F_LANGUAGE || REPLACE(F_TEXT_CODE,'UKOES1','UKOES03'),
F_TEXT_CODE = REPLACE(F_TEXT_CODE,'UKOES1','UKOES03')
WHERE F_PREFIX = 'UKOES'
AND F_TEXT_CODE IN ('UKOES16','UKOES17','UKOES18');


UPDATE T_COMP_TEXT
SET F_TEXT_CODE = REPLACE(F_TEXT_CODE,'UKOES1','UKOES03')
WHERE F_DATA_CODE = 'UKOES'
AND F_TEXT_CODE IN ('UKOES16','UKOES17','UKOES18');


UPDATE T_TEXT_DETAILS
SET F_TEXT_KEY = F_LANGUAGE || REPLACE(F_TEXT_CODE,'SYM','SYM00'),
F_TEXT_CODE = REPLACE(F_TEXT_CODE,'SYM','SYM00')
WHERE F_PREFIX = 'SYM'
AND F_TEXT_TYPE = 'TX';

UPDATE T_TEXT_DETAILS
SET F_TEXT_KEY = F_LANGUAGE || REPLACE(F_TEXT_CODE,'RCRA','RCRA0'),
F_TEXT_CODE = REPLACE(F_TEXT_CODE,'RCRA','RCRA0')
WHERE F_PREFIX = 'RCRA'
AND F_TEXT_TYPE = 'TX';

UPDATE T_PROD_TEXT
SET F_TEXT_CODE = REPLACE(F_TEXT_CODE,'RCRA','RCRA0')
WHERE F_DATA_CODE = 'RCRA'
AND F_TEXT_CODE = 'RCRA001';


UPDATE T_TEXT_DETAILS
SET F_TEXT_KEY = F_LANGUAGE || REPLACE(F_TEXT_CODE,'NPRI00','NPRI003'),
F_TEXT_CODE = REPLACE(F_TEXT_CODE,'NPRI00','NPRI003')
WHERE F_PREFIX = 'NPRI'
AND F_TEXT_CODE IN ('NPRI001','NPRI002','NPRI003');


UPDATE T_PROD_TEXT
SET F_TEXT_CODE = REPLACE(F_TEXT_CODE,'NPRI00','NPRI003')
WHERE F_DATA_CODE = 'NPRI'
AND F_TEXT_CODE IN ('NPRI001','NPRI002','NPRI003');



UPDATE T_TEXT_DETAILS
SET F_TEXT_KEY = F_LANGUAGE || 'NDSL0001',
F_TEXT_CODE = 'NDSL0001'
WHERE F_PREFIX = 'NDSL'
AND F_TEXT_CODE = 'NDSL001';


UPDATE T_PROD_TEXT
SET F_TEXT_CODE = 'NDSL0001'
WHERE F_DATA_CODE = 'NDSL'
AND F_TEXT_CODE = 'NDSL001';



UPDATE T_TEXT_DETAILS
SET F_TEXT_KEY = F_LANGUAGE || 'NDSL9999',
F_TEXT_CODE = 'NDSL9999'
WHERE F_PREFIX = 'NDSL'
AND F_TEXT_CODE = 'NDSL999';


UPDATE T_PROD_TEXT
SET F_TEXT_CODE = 'NDSL9999'
WHERE F_DATA_CODE = 'NDSL'
AND F_TEXT_CODE = 'NDSL999';


UPDATE T_TEXT_DETAILS
SET F_TEXT_KEY = F_LANGUAGE || REPLACE(F_TEXT_CODE,'NDSL0','NDSL01'),
F_TEXT_CODE = REPLACE(F_TEXT_CODE,'NDSL0','NDSL01')
WHERE F_PREFIX = 'NDSL'
AND F_TEXT_TYPE = 'TX'
AND LENGTH(F_TEXT_CODE) = 7;

UPDATE T_PROD_TEXT
SET F_TEXT_CODE = REPLACE(F_TEXT_CODE,'NDSL0','NDSL01')
WHERE F_DATA_CODE = 'NDSL'
AND LENGTH(F_TEXT_CODE) = 7;





UPDATE T_TEXT_DETAILS
SET F_TEXT_LINE = '  '
WHERE F_TEXT_LINE IS NULL;


INSERT INTO T_TEXT_DETAILS
(F_TEXT_KEY,F_LANGUAGE,F_TEXT_CODE,F_TEXT_LINE,F_TEXT_TYPE,F_PREFIX,F_USER_ID,
F_DATE_STAMP, F_TIME)
SELECT A.F_LANGUAGE||B.F_TEXT_CODE,A.F_LANGUAGE,B.F_TEXT_CODE,'  ',B.F_TEXT_TYPE,
B.F_PREFIX,B.F_USER_ID,B.F_DATE_STAMP, B.F_TIME
FROM T_LANGUAGES A, T_TEXT_DETAILS B
WHERE A.F_LANGUAGE != 'EN'
AND B.F_LANGUAGE = 'EN'
AND NOT EXISTS (SELECT 'X' FROM T_TEXT_DETAILS C
WHERE C.F_TEXT_KEY = A.F_LANGUAGE || B.F_TEXT_CODE);

DELETE T_TEXT_HEADERS WHERE NOT EXISTS (SELECT 'X'
FROM T_TEXT_DETAILS A WHERE A.F_TEXT_CODE = T_TEXT_HEADERS.F_TEXT_CODE);

INSERT INTO  T_TEXT_HEADERS
(
F_TEXT_CODE,
F_DATE_UPDATED,
F_TIME_UPDATED,
F_USER_UPDATED,
F_SEVERITY
)
SELECT F_TEXT_CODE, SYSDATE, SYSDATE, 'TEXT', 0 FROM T_TEXT_DETAILS A
WHERE A.F_LANGUAGE = 'EN'
AND  NOT EXISTS
(SELECT 'X' FROM T_TEXT_HEADERS 
WHERE F_TEXT_CODE = A.F_TEXT_CODE);


COMMIT;


SPOOL OFF;
