SPOOL c:\oratemp\registeredtrademark61.log

UPDATE T_PRODUCT_ALIAS_NAMES SET F_ALIAS_NAME=REPLACE(F_ALIAS_NAME,'|SUPER','|sup')
WHERE F_ALIAS_NAME LIKE '%|SUPER%';
 
UPDATE T_PRODUCT_ALIAS_NAMES SET F_ALIAS_NAME=REPLACE(F_ALIAS_NAME,'|NOSUPERSUB','|sup0')
WHERE F_ALIAS_NAME LIKE '%|NOSUPERSUB%';
 
UPDATE T_PRODUCT_ALIAS_NAMES SET F_ALIAS_NAME=REPLACE(F_ALIAS_NAME,'®','|TS')
WHERE F_ALIAS_NAME LIKE '%®%';

UPDATE T_PRODUCT_GROUPS SET F_PROD_GROUP_NAME=REPLACE(F_PROD_GROUP_NAME,'|SUPER','|sup')
WHERE F_PROD_GROUP_NAME LIKE '%|SUPER%';
 
UPDATE T_PRODUCT_GROUPS SET F_PROD_GROUP_NAME=REPLACE(F_PROD_GROUP_NAME,'|NOSUPERSUB','|sup0')
WHERE F_PROD_GROUP_NAME LIKE '%|NOSUPERSUB%';

UPDATE T_PRODUCT_GROUPS SET F_PROD_GROUP_NAME=REPLACE(F_PROD_GROUP_NAME,'®','|TS')
WHERE F_PROD_GROUP_NAME LIKE '%®%';

UPDATE T_PRODUCTS SET F_PRODUCT_NAME=REPLACE(F_PRODUCT_NAME,'|SUPER','|sup')
WHERE F_PRODUCT_NAME LIKE '%|SUPER%';
 
UPDATE T_PRODUCTS SET F_PRODUCT_NAME=REPLACE(F_PRODUCT_NAME,'|NOSUPERSUB','|sup0')
WHERE F_PRODUCT_NAME LIKE '%|NOSUPERSUB%';
 
UPDATE T_PRODUCTS SET F_PRODUCT_NAME=REPLACE(F_PRODUCT_NAME,'®','|TS')
WHERE F_PRODUCT_NAME LIKE '%®%';

UPDATE T_ALIAS_LANGUAGE_NAMES SET F_ALIAS_NAME=REPLACE(F_ALIAS_NAME,'|SUPER','|sup')
WHERE F_ALIAS_NAME LIKE '%|SUPER%';
 
UPDATE T_ALIAS_LANGUAGE_NAMES SET F_ALIAS_NAME=REPLACE(F_ALIAS_NAME,'|NOSUPERSUB','|sup0')
WHERE F_ALIAS_NAME LIKE '%|NOSUPERSUB%';
 
UPDATE T_ALIAS_LANGUAGE_NAMES SET F_ALIAS_NAME=REPLACE(F_ALIAS_NAME,'®','|TS')
WHERE F_ALIAS_NAME LIKE '%®%';

UPDATE T_PHRASE_TRANSLATIONS SET F_PHRASE=REPLACE(F_PHRASE,'|SUPER','|sup')
WHERE F_PHRASE LIKE '%|SUPER%';
 
UPDATE T_PHRASE_TRANSLATIONS SET F_PHRASE=REPLACE(F_PHRASE,'|NOSUPERSUB','|sup0')
WHERE F_PHRASE LIKE '%|NOSUPERSUB%';
 
UPDATE T_PHRASE_TRANSLATIONS SET F_PHRASE=REPLACE(F_PHRASE,'®','|TS')
WHERE F_PHRASE LIKE '%®%';

UPDATE T_PROD_DATA SET F_DATA=REPLACE(F_DATA,'|SUPER','|sup')
WHERE F_DATA LIKE '%|SUPER%';
 
UPDATE T_PROD_DATA SET F_DATA=REPLACE(F_DATA,'|NOSUPERSUB','|sup0')
WHERE F_DATA LIKE '%|NOSUPERSUB%';
 
UPDATE T_PROD_DATA SET F_DATA=REPLACE(F_DATA,'®','|TS')
WHERE F_DATA LIKE '%®%';

UPDATE T_PDF_MSDS SET F_CUSTOM1=REPLACE(F_CUSTOM1,'|SUPER','|sup')
WHERE F_CUSTOM1 LIKE '%|SUPER%';
 
UPDATE T_PDF_MSDS SET F_CUSTOM1=REPLACE(F_CUSTOM1,'|NOSUPERSUB','|sup0')
WHERE F_CUSTOM1 LIKE '%|NOSUPERSUB%';
 
UPDATE T_PDF_MSDS SET F_CUSTOM1=REPLACE(F_CUSTOM1,'®','|TS')
WHERE F_CUSTOM1 LIKE '%®%';

UPDATE T_PDF_MSDS SET F_CUSTOM2=REPLACE(F_CUSTOM2,'|SUPER','|sup')
WHERE F_CUSTOM2 LIKE '%|SUPER%';
 
UPDATE T_PDF_MSDS SET F_CUSTOM2=REPLACE(F_CUSTOM2,'|NOSUPERSUB','|sup0')
WHERE F_CUSTOM2 LIKE '%|NOSUPERSUB%';
 
UPDATE T_PDF_MSDS SET F_CUSTOM2=REPLACE(F_CUSTOM2,'®','|TS')
WHERE F_CUSTOM2 LIKE '%®%';

UPDATE T_PDF_MSDS SET F_CUSTOM3=REPLACE(F_CUSTOM3,'|SUPER','|sup')
WHERE F_CUSTOM3 LIKE '%|SUPER%';
 
UPDATE T_PDF_MSDS SET F_CUSTOM3=REPLACE(F_CUSTOM3,'|NOSUPERSUB','|sup0')
WHERE F_CUSTOM3 LIKE '%|NOSUPERSUB%';
 
UPDATE T_PDF_MSDS SET F_CUSTOM3=REPLACE(F_CUSTOM3,'®','|TS')
WHERE F_CUSTOM3 LIKE '%®%';

UPDATE T_PDF_MSDS SET F_CUSTOM4=REPLACE(F_CUSTOM4,'|SUPER','|sup')
WHERE F_CUSTOM4 LIKE '%|SUPER%';
 
UPDATE T_PDF_MSDS SET F_CUSTOM4=REPLACE(F_CUSTOM4,'|NOSUPERSUB','|sup0')
WHERE F_CUSTOM4 LIKE '%|NOSUPERSUB%';
 
UPDATE T_PDF_MSDS SET F_CUSTOM4=REPLACE(F_CUSTOM4,'®','|TS')
WHERE F_CUSTOM4 LIKE '%®%';

UPDATE T_PDF_MSDS SET F_CUSTOM5=REPLACE(F_CUSTOM5,'|SUPER','|sup')
WHERE F_CUSTOM5 LIKE '%|SUPER%';
 
UPDATE T_PDF_MSDS SET F_CUSTOM5=REPLACE(F_CUSTOM5,'|NOSUPERSUB','|sup0')
WHERE F_CUSTOM5 LIKE '%|NOSUPERSUB%';
 
UPDATE T_PDF_MSDS SET F_CUSTOM5=REPLACE(F_CUSTOM5,'®','|TS')
WHERE F_CUSTOM5 LIKE '%®%';

UPDATE T_PDF_MSDS SET F_PRODUCT_NAME=REPLACE(F_PRODUCT_NAME,'|SUPER','|sup')
WHERE F_PRODUCT_NAME LIKE '%|SUPER%';
 
UPDATE T_PDF_MSDS SET F_PRODUCT_NAME=REPLACE(F_PRODUCT_NAME,'|NOSUPERSUB','|sup0')
WHERE F_PRODUCT_NAME LIKE '%|NOSUPERSUB%';
 
UPDATE T_PDF_MSDS SET F_PRODUCT_NAME=REPLACE(F_PRODUCT_NAME,'®','|TS')
WHERE F_PRODUCT_NAME LIKE '%®%';

UPDATE T_RTF_MSDS SET F_CUSTOM1=REPLACE(F_CUSTOM1,'|SUPER','|sup')
WHERE F_CUSTOM1 LIKE '%|SUPER%';
 
UPDATE T_RTF_MSDS SET F_CUSTOM1=REPLACE(F_CUSTOM1,'|NOSUPERSUB','|sup0')
WHERE F_CUSTOM1 LIKE '%|NOSUPERSUB%';
 
UPDATE T_RTF_MSDS SET F_CUSTOM1=REPLACE(F_CUSTOM1,'®','|TS')
WHERE F_CUSTOM1 LIKE '%®%';

UPDATE T_RTF_MSDS SET F_CUSTOM2=REPLACE(F_CUSTOM2,'|SUPER','|sup')
WHERE F_CUSTOM2 LIKE '%|SUPER%';
 
UPDATE T_RTF_MSDS SET F_CUSTOM2=REPLACE(F_CUSTOM2,'|NOSUPERSUB','|sup0')
WHERE F_CUSTOM2 LIKE '%|NOSUPERSUB%';
 
UPDATE T_RTF_MSDS SET F_CUSTOM2=REPLACE(F_CUSTOM2,'®','|TS')
WHERE F_CUSTOM2 LIKE '%®%';

UPDATE T_RTF_MSDS SET F_CUSTOM3=REPLACE(F_CUSTOM3,'|SUPER','|sup')
WHERE F_CUSTOM3 LIKE '%|SUPER%';
 
UPDATE T_RTF_MSDS SET F_CUSTOM3=REPLACE(F_CUSTOM3,'|NOSUPERSUB','|sup0')
WHERE F_CUSTOM3 LIKE '%|NOSUPERSUB%';
 
UPDATE T_RTF_MSDS SET F_CUSTOM3=REPLACE(F_CUSTOM3,'®','|TS')
WHERE F_CUSTOM3 LIKE '%®%';

UPDATE T_RTF_MSDS SET F_CUSTOM4=REPLACE(F_CUSTOM4,'|SUPER','|sup')
WHERE F_CUSTOM4 LIKE '%|SUPER%';
 
UPDATE T_RTF_MSDS SET F_CUSTOM4=REPLACE(F_CUSTOM4,'|NOSUPERSUB','|sup0')
WHERE F_CUSTOM4 LIKE '%|NOSUPERSUB%';
 
UPDATE T_RTF_MSDS SET F_CUSTOM4=REPLACE(F_CUSTOM4,'®','|TS')
WHERE F_CUSTOM4 LIKE '%®%';

UPDATE T_RTF_MSDS SET F_CUSTOM5=REPLACE(F_CUSTOM5,'|SUPER','|sup')
WHERE F_CUSTOM5 LIKE '%|SUPER%';
 
UPDATE T_RTF_MSDS SET F_CUSTOM5=REPLACE(F_CUSTOM5,'|NOSUPERSUB','|sup0')
WHERE F_CUSTOM5 LIKE '%|NOSUPERSUB%';
 
UPDATE T_RTF_MSDS SET F_CUSTOM5=REPLACE(F_CUSTOM5,'®','|TS')
WHERE F_CUSTOM5 LIKE '%®%';

UPDATE T_RTF_MSDS SET F_PRODUCT_NAME=REPLACE(F_PRODUCT_NAME,'|SUPER','|sup')
WHERE F_PRODUCT_NAME LIKE '%|SUPER%';
 
UPDATE T_RTF_MSDS SET F_PRODUCT_NAME=REPLACE(F_PRODUCT_NAME,'|NOSUPERSUB','|sup0')
WHERE F_PRODUCT_NAME LIKE '%|NOSUPERSUB%';
 
UPDATE T_RTF_MSDS SET F_PRODUCT_NAME=REPLACE(F_PRODUCT_NAME,'®','|TS')
WHERE F_PRODUCT_NAME LIKE '%®%';

UPDATE T_HTML_MSDS SET F_CUSTOM1=REPLACE(F_CUSTOM1,'|SUPER','|sup')
WHERE F_CUSTOM1 LIKE '%|SUPER%';
 
UPDATE T_HTML_MSDS SET F_CUSTOM1=REPLACE(F_CUSTOM1,'|NOSUPERSUB','|sup0')
WHERE F_CUSTOM1 LIKE '%|NOSUPERSUB%';
 
UPDATE T_HTML_MSDS SET F_CUSTOM1=REPLACE(F_CUSTOM1,'®','|TS')
WHERE F_CUSTOM1 LIKE '%®%';

UPDATE T_HTML_MSDS SET F_CUSTOM2=REPLACE(F_CUSTOM2,'|SUPER','|sup')
WHERE F_CUSTOM2 LIKE '%|SUPER%';
 
UPDATE T_HTML_MSDS SET F_CUSTOM2=REPLACE(F_CUSTOM2,'|NOSUPERSUB','|sup0')
WHERE F_CUSTOM2 LIKE '%|NOSUPERSUB%';
 
UPDATE T_HTML_MSDS SET F_CUSTOM2=REPLACE(F_CUSTOM2,'®','|TS')
WHERE F_CUSTOM2 LIKE '%®%';

UPDATE T_HTML_MSDS SET F_CUSTOM3=REPLACE(F_CUSTOM3,'|SUPER','|sup')
WHERE F_CUSTOM3 LIKE '%|SUPER%';
 
UPDATE T_HTML_MSDS SET F_CUSTOM3=REPLACE(F_CUSTOM3,'|NOSUPERSUB','|sup0')
WHERE F_CUSTOM3 LIKE '%|NOSUPERSUB%';
 
UPDATE T_HTML_MSDS SET F_CUSTOM3=REPLACE(F_CUSTOM3,'®','|TS')
WHERE F_CUSTOM3 LIKE '%®%';

UPDATE T_HTML_MSDS SET F_CUSTOM4=REPLACE(F_CUSTOM4,'|SUPER','|sup')
WHERE F_CUSTOM4 LIKE '%|SUPER%';
 
UPDATE T_HTML_MSDS SET F_CUSTOM4=REPLACE(F_CUSTOM4,'|NOSUPERSUB','|sup0')
WHERE F_CUSTOM4 LIKE '%|NOSUPERSUB%';
 
UPDATE T_HTML_MSDS SET F_CUSTOM4=REPLACE(F_CUSTOM4,'®','|TS')
WHERE F_CUSTOM4 LIKE '%®%';

UPDATE T_HTML_MSDS SET F_CUSTOM5=REPLACE(F_CUSTOM5,'|SUPER','|sup')
WHERE F_CUSTOM5 LIKE '%|SUPER%';
 
UPDATE T_HTML_MSDS SET F_CUSTOM5=REPLACE(F_CUSTOM5,'|NOSUPERSUB','|sup0')
WHERE F_CUSTOM5 LIKE '%|NOSUPERSUB%';
 
UPDATE T_HTML_MSDS SET F_CUSTOM5=REPLACE(F_CUSTOM5,'®','|TS')
WHERE F_CUSTOM5 LIKE '%®%';

UPDATE T_HTML_MSDS SET F_PRODUCT_NAME=REPLACE(F_PRODUCT_NAME,'|SUPER','|sup')
WHERE F_PRODUCT_NAME LIKE '%|SUPER%';
 
UPDATE T_HTML_MSDS SET F_PRODUCT_NAME=REPLACE(F_PRODUCT_NAME,'|NOSUPERSUB','|sup0')
WHERE F_PRODUCT_NAME LIKE '%|NOSUPERSUB%';
 
UPDATE T_HTML_MSDS SET F_PRODUCT_NAME=REPLACE(F_PRODUCT_NAME,'®','|TS')
WHERE F_PRODUCT_NAME LIKE '%®%';



COMMIT;

SPOOL OFF;

