show serveroutput

SPOOL C:\ORATEMP\RegTradeMarkCursor.log

DECLARE
  CURSOR c_PAN IS
    SELECT F_ALIAS FROM T_PRODUCT_ALIAS_NAMES WHERE F_ALIAS_NAME LIKE '%|SUPER%' OR F_ALIAS_NAME LIKE '%|NOSUPERSUB' OR F_ALIAS_NAME LIKE '%®%';

  CURSOR c_PG IS
    SELECT F_PRODUCT_GROUP FROM T_PRODUCT_GROUPS WHERE F_PROD_GROUP_NAME LIKE '%|SUPER%' OR F_PROD_GROUP_NAME LIKE '%|NOSUPERSUB%' OR F_PROD_GROUP_NAME LIKE '%®%';

  CURSOR c_PROD IS
    SELECT F_PRODUCT FROM T_PRODUCTS WHERE F_PRODUCT_NAME LIKE '%|SUPER%' OR F_PRODUCT_NAME LIKE '%|NOSUPERSUB%' OR F_PRODUCT_NAME LIKE '%®%';

  CURSOR c_ALN IS
    SELECT F_ALIAS, F_LANGUAGE FROM T_ALIAS_LANGUAGE_NAMES WHERE F_ALIAS_NAME LIKE '%|SUPER%' OR F_ALIAS_NAME LIKE '%|NOSUPERSUB%' OR F_ALIAS_NAME LIKE '%®%';

  CURSOR c_TXTLN IS
    SELECT F_TEXT_KEY FROM T_TEXT_DETAILS WHERE F_TEXT_LINE LIKE '%|SUPER%' OR F_TEXT_LINE LIKE '%|NOSUPERSUB%' OR F_TEXT_LINE LIKE '%®%';

  CURSOR c_PD IS
    SELECT F_PRODUCT, F_DATA_CODE FROM T_PROD_DATA WHERE F_DATA LIKE '%|SUPER%' OR F_DATA LIKE '%|NOSUPERSUB%' OR F_DATA LIKE '%®%';

  CURSOR c_PDF IS
    SELECT F_PRODUCT, F_LANGUAGE, F_FORMAT, F_SUBFORMAT, F_DATE_STAMP, F_PLANT, F_DOC_TYPE FROM T_PDF_MSDS;

  CURSOR c_RTF IS
    SELECT F_PRODUCT, F_LANGUAGE, F_FORMAT, F_SUBFORMAT, F_DATE_STAMP, F_PLANT, F_DOC_TYPE FROM T_RTF_MSDS;

  CURSOR c_HTML IS
    SELECT F_PRODUCT, F_LANGUAGE, F_FORMAT, F_SUBFORMAT, F_DATE_STAMP, F_PLANT, F_DOC_TYPE FROM T_HTML_MSDS;


  COMMIT_COUNT NUMBER(20) DEFAULT 0;


BEGIN

  DBMS_OUTPUT.PUT_LINE('T_PRODUCT_ALIAS_NAMES');

  FOR REC IN c_PAN
  LOOP
    UPDATE T_PRODUCT_ALIAS_NAMES SET F_ALIAS_NAME = REPLACE(REPLACE(REPLACE(F_ALIAS_NAME,'|SUPER','|sup'),'|NOSUPERSUB','|sup0'),'®','|TS')
     WHERE F_ALIAS = REC.F_ALIAS;
 
    COMMIT_COUNT := COMMIT_COUNT + 1;

    --COMMIT every 1000 records
    IF MOD(COMMIT_COUNT, 1000) = 0 THEN
       COMMIT;
    END IF;

  END LOOP;

  COMMIT;

  COMMIT_COUNT := 0;


  DBMS_OUTPUT.PUT_LINE('T_PRODUCT_GROUPS');

  FOR REC IN c_PG
  LOOP
    UPDATE T_PRODUCT_GROUPS SET F_PROD_GROUP_NAME = REPLACE(REPLACE(REPLACE(F_PROD_GROUP_NAME,'|SUPER','|sup'),'|NOSUPERSUB','|sup0'),'®','|TS')
     WHERE F_PRODUCT_GROUP = REC.F_PRODUCT_GROUP ;
 
    COMMIT_COUNT := COMMIT_COUNT + 1;

    --COMMIT every 1000 records
    IF MOD(COMMIT_COUNT, 1000) = 0 THEN
       COMMIT;
    END IF;

  END LOOP;

  COMMIT;

  COMMIT_COUNT := 0;


  DBMS_OUTPUT.PUT_LINE('T_PRODUCTS');

  FOR REC IN c_PROD
  LOOP
    UPDATE T_PRODUCTS SET F_PRODUCT_NAME = REPLACE(REPLACE(REPLACE(F_PRODUCT_NAME,'|SUPER','|sup'),'|NOSUPERSUB','|sup0'),'®','|TS')
     WHERE F_PRODUCT = REC.F_PRODUCT;
 
    COMMIT_COUNT := COMMIT_COUNT + 1;

    --COMMIT every 1000 records
    IF MOD(COMMIT_COUNT, 1000) = 0 THEN
       COMMIT;
    END IF;

  END LOOP;

  COMMIT;

  COMMIT_COUNT := 0;


  DBMS_OUTPUT.PUT_LINE('T_ALIAS__LANGUAGE_NAMES');

  FOR REC IN c_ALN
  LOOP
    UPDATE T_ALIAS_LANGUAGE_NAMES SET F_ALIAS_NAME = REPLACE(REPLACE(REPLACE(F_ALIAS_NAME,'|SUPER','|sup'),'|NOSUPERSUB','|sup0'),'®','|TS')
     WHERE F_ALIAS = REC.F_ALIAS AND F_LANGUAGE = REC.F_LANGUAGE;
 
    COMMIT_COUNT := COMMIT_COUNT + 1;

    --COMMIT every 1000 records
    IF MOD(COMMIT_COUNT, 1000) = 0 THEN
       COMMIT;
    END IF;

  END LOOP;

  COMMIT;

  COMMIT_COUNT := 0;


  DBMS_OUTPUT.PUT_LINE('T_TEXT_DETAILS');

  FOR REC IN c_TXTLN
  LOOP
    UPDATE T_TEXT_DETAILS SET F_TEXT_LINE = REPLACE(REPLACE(REPLACE(F_TEXT_LINE,'|SUPER','|sup'),'|NOSUPERSUB','|sup0'),'®','|TS')
     WHERE F_TEXT_KEY = REC.F_TEXT_KEY;
 
    COMMIT_COUNT := COMMIT_COUNT + 1;

    --COMMIT every 1000 records
    IF MOD(COMMIT_COUNT, 1000) = 0 THEN
       COMMIT;
    END IF;

  END LOOP;

  COMMIT;

  COMMIT_COUNT := 0;


  DBMS_OUTPUT.PUT_LINE('T_PROD_DATA');

  FOR REC IN c_PD
  LOOP
    UPDATE T_PROD_DATA SET F_DATA = REPLACE(REPLACE(REPLACE(F_DATA,'|SUPER','|sup'),'|NOSUPERSUB','|sup0'),'®','|TS')
     WHERE F_PRODUCT = REC.F_PRODUCT AND F_DATA_CODE = REC.F_DATA_CODE;
 
    COMMIT_COUNT := COMMIT_COUNT + 1;

    --COMMIT every 1000 records
    IF MOD(COMMIT_COUNT, 1000) = 0 THEN
       COMMIT;
    END IF;

  END LOOP;

  COMMIT;

  COMMIT_COUNT := 0;



  DBMS_OUTPUT.PUT_LINE('T_PDF_MSDS');

  FOR REC IN c_PDF
  LOOP
    UPDATE T_PDF_MSDS 
     SET F_CUSTOM1 = REPLACE(REPLACE(REPLACE(F_CUSTOM1,'|SUPER','|sup'),'|NOSUPERSUB','|sup0'),'®','|TS'),
         F_CUSTOM2 = REPLACE(REPLACE(REPLACE(F_CUSTOM2,'|SUPER','|sup'),'|NOSUPERSUB','|sup0'),'®','|TS'),
         F_CUSTOM3 = REPLACE(REPLACE(REPLACE(F_CUSTOM3,'|SUPER','|sup'),'|NOSUPERSUB','|sup0'),'®','|TS'),
         F_CUSTOM4 = REPLACE(REPLACE(REPLACE(F_CUSTOM4,'|SUPER','|sup'),'|NOSUPERSUB','|sup0'),'®','|TS'),
         F_CUSTOM5 = REPLACE(REPLACE(REPLACE(F_CUSTOM5,'|SUPER','|sup'),'|NOSUPERSUB','|sup0'),'®','|TS'),
         F_PRODUCT_NAME = REPLACE(REPLACE(REPLACE(F_PRODUCT_NAME,'|SUPER','|sup'),'|NOSUPERSUB','|sup0'),'®','|TS')
     WHERE F_PRODUCT = REC.F_PRODUCT
       AND F_LANGUAGE = REC.F_LANGUAGE
       AND F_FORMAT = REC.F_FORMAT
       AND F_SUBFORMAT = REC.F_SUBFORMAT
       AND F_DATE_STAMP = REC.F_DATE_STAMP
       AND F_PLANT = REC.F_PLANT
       AND F_DOC_TYPE = REC.F_DOC_TYPE;

    COMMIT_COUNT := COMMIT_COUNT + 1;

    --COMMIT every 1000 records
    IF MOD(COMMIT_COUNT, 1000) = 0 THEN
       COMMIT;
    END IF;

  END LOOP;

  COMMIT;

  COMMIT_COUNT := 0;


  DBMS_OUTPUT.PUT_LINE('T_RTF_MSDS');

  FOR REC IN c_RTF
  LOOP
    UPDATE T_RTF_MSDS 
     SET F_CUSTOM1 = REPLACE(REPLACE(REPLACE(F_CUSTOM1,'|SUPER','|sup'),'|NOSUPERSUB','|sup0'),'®','|TS'),
         F_CUSTOM2 = REPLACE(REPLACE(REPLACE(F_CUSTOM2,'|SUPER','|sup'),'|NOSUPERSUB','|sup0'),'®','|TS'),
         F_CUSTOM3 = REPLACE(REPLACE(REPLACE(F_CUSTOM3,'|SUPER','|sup'),'|NOSUPERSUB','|sup0'),'®','|TS'),
         F_CUSTOM4 = REPLACE(REPLACE(REPLACE(F_CUSTOM4,'|SUPER','|sup'),'|NOSUPERSUB','|sup0'),'®','|TS'),
         F_CUSTOM5 = REPLACE(REPLACE(REPLACE(F_CUSTOM5,'|SUPER','|sup'),'|NOSUPERSUB','|sup0'),'®','|TS'),
         F_PRODUCT_NAME = REPLACE(REPLACE(REPLACE(F_PRODUCT_NAME,'|SUPER','|sup'),'|NOSUPERSUB','|sup0'),'®','|TS')
     WHERE F_PRODUCT = REC.F_PRODUCT
       AND F_LANGUAGE = REC.F_LANGUAGE
       AND F_FORMAT = REC.F_FORMAT
       AND F_SUBFORMAT = REC.F_SUBFORMAT
       AND F_DATE_STAMP = REC.F_DATE_STAMP
       AND F_PLANT = REC.F_PLANT
       AND F_DOC_TYPE = REC.F_DOC_TYPE;

    COMMIT_COUNT := COMMIT_COUNT + 1;

    --COMMIT every 1000 records
    IF MOD(COMMIT_COUNT, 1000) = 0 THEN
       COMMIT;
    END IF;

  END LOOP;

  COMMIT;

  COMMIT_COUNT := 0;


  DBMS_OUTPUT.PUT_LINE('T_HTML_MSDS');

  FOR REC IN c_HTML
  LOOP
    UPDATE T_HTML_MSDS 
     SET F_CUSTOM1 = REPLACE(REPLACE(REPLACE(F_CUSTOM1,'|SUPER','|sup'),'|NOSUPERSUB','|sup0'),'®','|TS'),
         F_CUSTOM2 = REPLACE(REPLACE(REPLACE(F_CUSTOM2,'|SUPER','|sup'),'|NOSUPERSUB','|sup0'),'®','|TS'),
         F_CUSTOM3 = REPLACE(REPLACE(REPLACE(F_CUSTOM3,'|SUPER','|sup'),'|NOSUPERSUB','|sup0'),'®','|TS'),
         F_CUSTOM4 = REPLACE(REPLACE(REPLACE(F_CUSTOM4,'|SUPER','|sup'),'|NOSUPERSUB','|sup0'),'®','|TS'),
         F_CUSTOM5 = REPLACE(REPLACE(REPLACE(F_CUSTOM5,'|SUPER','|sup'),'|NOSUPERSUB','|sup0'),'®','|TS'),
         F_PRODUCT_NAME = REPLACE(REPLACE(REPLACE(F_PRODUCT_NAME,'|SUPER','|sup'),'|NOSUPERSUB','|sup0'),'®','|TS')
     WHERE F_PRODUCT = REC.F_PRODUCT
       AND F_LANGUAGE = REC.F_LANGUAGE
       AND F_FORMAT = REC.F_FORMAT
       AND F_SUBFORMAT = REC.F_SUBFORMAT
       AND F_DATE_STAMP = REC.F_DATE_STAMP
       AND F_PLANT = REC.F_PLANT
       AND F_DOC_TYPE = REC.F_DOC_TYPE;

    COMMIT_COUNT := COMMIT_COUNT + 1;

    --COMMIT every 1000 records
    IF MOD(COMMIT_COUNT, 1000) = 0 THEN
       COMMIT;
    END IF;

  END LOOP;

  COMMIT;

  COMMIT_COUNT := 0;




END;
/


SPOOL OFF;

