SET TERMOUT OFF
SET PAGESIZE 0
SET TRIMSPOOL ON
SET LINESIZE 100
SET FEEDBACK OFF


SET HEAD OFF;
SPOOL c:\oratemp\DisableRI.sql

prompt SPOOL c:\oratemp\DisableRI.log;
select 'ALTER TABLE ' || table_name || ' MODIFY CONSTRAINT ' || constraint_name || ' DISABLE;'
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_TYPE = 'R'
ORDER BY TABLE_NAME, CONSTRAINT_NAME;

prompt SPOOL OFF;;

SPOOL OFF;



SPOOL c:\oratemp\EnableRI.sql

prompt SPOOL c:\oratemp\EnableRI.log;
select 'ALTER TABLE ' || table_name || ' MODIFY CONSTRAINT ' || constraint_name || ' ENABLE;'
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_TYPE = 'R'
ORDER BY TABLE_NAME, CONSTRAINT_NAME;

prompt SPOOL OFF;;

SPOOL OFF;

SET LINESIZE 80
SET PAGESIZE 24
SET TERMOUT ON
SET FEEDBACK ON
