SPOOL C:\oratemp\ENABLEITrigs.log

ALTER TRIGGER I_ALIASES_TRIG ENABLE;
ALTER TRIGGER I_ATTRIBUTES_TRIG ENABLE;
ALTER TRIGGER I_COMPONENTS_TRIG ENABLE;
ALTER TRIGGER I_DOCUMENTS_TRIG ENABLE;
ALTER TRIGGER I_ETLLOG_TRIG ENABLE;
ALTER TRIGGER I_FORMULATIONS_TRIG ENABLE;
ALTER TRIGGER I_ORDERS_TRIG ENABLE;
ALTER TRIGGER I_PHRASES_TRIG ENABLE;
ALTER TRIGGER I_PROCESS_TRIG ENABLE;
ALTER TRIGGER I_PROCESSES_TRIG ENABLE;
ALTER TRIGGER I_PROCESS_GROUPS_TRIG ENABLE;
ALTER TRIGGER I_PROCESS_GROUP_MEMBERS_TRIG ENABLE;
ALTER TRIGGER I_PRODUCTS_TRIG ENABLE;
ALTER TRIGGER I_PRODUCT_GROUPS_TRIG ENABLE;
ALTER TRIGGER I_PRODUCT_GROUP_MEMBERS_TRIG ENABLE;
ALTER TRIGGER I_LABELS_TRIG ENABLE;
ALTER TRIGGER I_LABEL_DETAILS_TRIG ENABLE;
ALTER TRIGGER I_LABEL_PRINTERS_TRIG ENABLE;
ALTER TRIGGER I_LOLI_LOAD_TRIG ENABLE;
ALTER TRIGGER I_SUPPLIERS_TRIG ENABLE;

spool off;

