DECLARE @@Format@@ VARCHAR(3) = 'MTR'
DECLARE @@SubFormat@@ VARCHAR(6) = 'MTR'

select 'List of textcodes/datacodes'

/* Extract Spreadsheet of reserved families */
SELECT DISTINCT L.F_TEXT_CODE, T.F_PHRASE, L.F_DATA_CODE
FROM T_PHRASE_LINKAGE L
JOIN T_PHRASE_TRANSLATIONS T
ON T.F_PHRASE_ID = L.F_PHRASE_ID
AND T.F_LANGUAGE = 'EN'
JOIN T_DATATYPES D
ON D.F_DATA_CODE = L.F_DATA_CODE
JOIN T_MSDSTYPE_SECTIONS M
ON M.F_FORMAT = D.F_FORMAT
AND M.F_SECTION = D.F_SECTION
JOIN T_GCS_RESERVED_DATA_CODES GCS
ON GCS.F_DATA_CODE = L.F_DATA_CODE
WHERE M.F_FORMAT = @@Format@@
AND M.F_MSDSTYPE IN ('GHSD',@@SubFormat@@,LEFT(@@SubFormat@@,LEN(@@SubFormat@@)-1)+'D')
ORDER BY L.F_DATA_CODE, T.F_PHRASE, L.F_TEXT_CODE

/* MSSQL Analysis */
SELECT 'SELECT '
+CHAR(13)+CHAR(10)+'(SELECT COUNT(F_TEXT_CODE) FROM T_PROD_TEXT WHERE F_TEXT_CODE = L.F_TEXT_CODE) "In Products" '
+CHAR(13)+CHAR(10)+', (SELECT COUNT(F_TEXT_CODE) FROM T_PROD_ALIAS_TEXT WHERE F_TEXT_CODE = L.F_TEXT_CODE) "In Aliases" '
+CHAR(13)+CHAR(10)+', (SELECT COUNT(F_TEXT_CODE) FROM T_COMP_TEXT WHERE F_TEXT_CODE = L.F_TEXT_CODE) "In Components" '
+CHAR(13)+CHAR(10)+', (SELECT COUNT(DATA) FROM T_MSDSTYPE_SECTIONS MS JOIN T_DATATYPES D ON D.F_FORMAT = MS.F_FORMAT AND D.F_SECTION = MS.F_SECTION AND (D.F_DATA_CODE = ''XGROUP'' OR D.F_DATA_CODE = L.F_DATA_CODE) OUTER APPLY (SELECT * FROM SPLIT(REPLACE(D.F_DEFAULT_CODE,''|'',''''),'';'') WHERE D.F_FORMAT = MS.F_FORMAT AND D.F_SECTION = MS.F_SECTION AND D.F_DEFAULT_CODE <> '''' AND (D.F_DATA_CODE = ''XGROUP'' OR D.F_DATA_CODE = L.F_DATA_CODE) AND REPLACE(D.F_DEFAULT_CODE,''|'','''') LIKE ''%''+L.F_TEXT_CODE+''%'') DS WHERE DS.DATA = L.F_TEXT_CODE) "In Defaults" '
+CHAR(13)+CHAR(10)+', L.F_DATA_CODE "Datacode in use" '
+CHAR(13)+CHAR(10)+', L.F_TEXT_CODE "Textcode in use" '
+CHAR(13)+CHAR(10)+', T.F_PHRASE "Current phrase" '
+CHAR(13)+CHAR(10)+', ''=INDEX(INDIRECT("B:B"),MATCH(INDIRECT(CONCAT("J",ROW())),INDIRECT("A:A"),0))'' "Reserved phrase" '
+CHAR(13)+CHAR(10)+', ''=EXACT(UPPER(INDIRECT(CONCAT("K",ROW()))),UPPER(INDIRECT(CONCAT("L",ROW()))))'' "Matches" '
+CHAR(13)+CHAR(10)+', ''=INDEX(INDIRECT(ADDRESS(MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),0),3,4)&":"&ADDRESS(IF(MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),1)=MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),0),MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),1),MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),1)),3,4)),MATCH(INDIRECT(CONCAT("K",ROW())),INDIRECT(ADDRESS(MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),0),2,4)&":"&ADDRESS(IF(MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),1)=MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),0),MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),1),MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),1)),2,4)),0),0)'' "Matching reserved datacode" '
+CHAR(13)+CHAR(10)+', ''=INDEX(INDIRECT(ADDRESS(MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),0),1,4)&":"&ADDRESS(IF(MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),1)=MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),0),MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),1),MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),1)),1,4)),MATCH(INDIRECT(CONCAT("K",ROW())),INDIRECT(ADDRESS(MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),0),2,4)&":"&ADDRESS(IF(MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),1)=MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),0),MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),1),MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),1)),2,4)),0),0)'' "Matching reserved textcode" '
+CHAR(13)+CHAR(10)+', ''=INDEX(INDIRECT("B:B"),MATCH(INDIRECT(CONCAT("O",ROW())),INDIRECT("A:A"),0))'' "Matching phrase" '
+CHAR(13)+CHAR(10)+', ''="UPD''+''ATE T_PROD_TEXT SET F_DATA_CODE = ''''"&INDIRECT(CONCAT("N",ROW()))&"'''', F_TEXT_CODE = ''''"&INDIRECT(CONCAT("O",ROW()))&"'''' WHERE F_DATA_CODE = ''''"&INDIRECT(CONCAT("I",ROW()))&"'''' AND F_TEXT_CODE = ''''"&INDIRECT(CONCAT("J",ROW()))&"''''"'' "Modify Products" '
+CHAR(13)+CHAR(10)+', ''="UPD''+''ATE T_PROD_ALIAS_TEXT SET F_DATA_CODE = ''''"&INDIRECT(CONCAT("N",ROW()))&"'''', F_TEXT_CODE = ''''"&INDIRECT(CONCAT("O",ROW()))&"'''' WHERE F_DATA_CODE = ''''"&INDIRECT(CONCAT("I",ROW()))&"'''' AND F_TEXT_CODE = ''''"&INDIRECT(CONCAT("J",ROW()))&"''''"'' "Modify Aliases" '
+CHAR(13)+CHAR(10)+', ''="UPD''+''ATE T_COMP_TEXT SET F_DATA_CODE = ''''"&INDIRECT(CONCAT("N",ROW()))&"'''', F_TEXT_CODE = ''''"&INDIRECT(CONCAT("O",ROW()))&"'''' WHERE F_DATA_CODE = ''''"&INDIRECT(CONCAT("I",ROW()))&"'''' AND F_TEXT_CODE = ''''"&INDIRECT(CONCAT("J",ROW()))&"''''"'' "Modify Components" '
+CHAR(13)+CHAR(10)+', STUFF((SELECT DISTINCT '', ''+MS.F_FORMAT+''/''+MS.F_MSDSTYPE+''/''+MS.F_SECTION FROM T_MSDSTYPE_SECTIONS MS JOIN T_DATATYPES D ON MS.F_FORMAT = D.F_FORMAT AND MS.F_SECTION = D.F_SECTION WHERE L.F_TEXT_CODE LIKE REPLACE(D.F_DEFAULT_CODE,''|'','''') ORDER BY 1 FOR XML PATH('''')),1,2,'''') "Defaults in use" '
+CHAR(13)+CHAR(10)+'FROM ('+STUFF((
SELECT DISTINCT 'UNION ALL SELECT '''+D.F_DATA_CODE+''' CODE '
FROM T_MSDSTYPE_SECTIONS M
JOIN T_DATATYPES D ON D.F_SECTION = M.F_SECTION AND D.F_FORMAT = M.F_FORMAT
JOIN T_GCS_RESERVED_DATA_CODES G ON G.F_DATA_CODE = D.F_DATA_CODE
WHERE M.F_FORMAT = @@Format@@
AND (M.F_MSDSTYPE = @@SubFormat@@ OR M.F_MSDSTYPE LIKE LEFT(@@SubFormat@@,LEN(@@SubFormat@@)-1)+'D' OR M.F_MSDSTYPE = 'GHSD')
ORDER BY 1 FOR XML PATH('')),1,10,'')+') DATA '
+CHAR(13)+CHAR(10)+'JOIN T_PHRASE_LINKAGE L ON L.F_DATA_CODE = DATA.CODE '
+CHAR(13)+CHAR(10)+'JOIN T_PHRASE_TRANSLATIONS T ON T.F_PHRASE_ID = L.F_PHRASE_ID AND T.F_LANGUAGE = ''EN'' '
+CHAR(13)+CHAR(10)+'LEFT JOIN ('+REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(STUFF((
SELECT DISTINCT 'UNION ALL SELECT '''+L.F_DATA_CODE+''' D, '''+REPLACE(REPLACE(REPLACE(REPLACE(T.F_PHRASE,CHAR(39),CHAR(39)+CHAR(39)),'insert','ins''+''ert'),'update','up''+''date'),'delete','del''+''ete')+''' P, '''+L.F_TEXT_CODE+''' T '
FROM T_MSDSTYPE_SECTIONS M
JOIN T_DATATYPES D ON D.F_SECTION = M.F_SECTION AND D.F_FORMAT = M.F_FORMAT
JOIN T_GCS_RESERVED_DATA_CODES G ON G.F_DATA_CODE = D.F_DATA_CODE
JOIN T_PHRASE_LINKAGE L ON L.F_DATA_CODE = G.F_DATA_CODE
JOIN T_PHRASE_TRANSLATIONS T ON T.F_PHRASE_ID = L.F_PHRASE_ID AND T.F_LANGUAGE = 'EN'
WHERE M.F_FORMAT = @@Format@@
AND (M.F_MSDSTYPE = @@SubFormat@@ OR M.F_MSDSTYPE LIKE LEFT(@@SubFormat@@,LEN(@@SubFormat@@)-1)+'D' OR M.F_MSDSTYPE = 'GHSD')
ORDER BY 1 FOR XML PATH('')),1,10,''),'&amp;','&'),'&lt;','<'),'&gt;','>'),'insert','ins''+''ert'),'update','upd''+''ate'),'delete','del''+''ete')+') E '
+CHAR(13)+CHAR(10)+'ON E.D = L.F_DATA_CODE AND E.T = L.F_TEXT_CODE AND REPLACE(REPLACE(E.P,''&lt;'',''<''),''&gt;'',''>'') = T.F_PHRASE '
+CHAR(13)+CHAR(10)+'WHERE E.T IS NULL '
+CHAR(13)+CHAR(10)+'AND EXISTS ('
+CHAR(13)+CHAR(10)+' SELECT 1 FROM T_PHRASE_LINKAGE A '
+CHAR(13)+CHAR(10)+' LEFT JOIN T_PROD_TEXT PT ON PT.F_DATA_CODE = A.F_DATA_CODE AND PT.F_TEXT_CODE = A.F_TEXT_CODE '
+CHAR(13)+CHAR(10)+' LEFT JOIN T_PROD_ALIAS_TEXT PAT ON PAT.F_DATA_CODE = A.F_DATA_CODE AND PAT.F_TEXT_CODE = A.F_TEXT_CODE '
+CHAR(13)+CHAR(10)+' LEFT JOIN T_COMP_TEXT CT ON CT.F_DATA_CODE = A.F_DATA_CODE AND CT.F_TEXT_CODE = A.F_TEXT_CODE '
+CHAR(13)+CHAR(10)+' CROSS JOIN T_MSDSTYPE_SECTIONS MS '
+CHAR(13)+CHAR(10)+' LEFT JOIN T_DATATYPES D ON D.F_FORMAT = MS.F_FORMAT AND D.F_SECTION = MS.F_SECTION AND (D.F_DATA_CODE = ''XGROUP'' OR D.F_DATA_CODE = L.F_DATA_CODE) '
+CHAR(13)+CHAR(10)+' OUTER APPLY (SELECT * FROM SPLIT(REPLACE(D.F_DEFAULT_CODE,''|'',''''),'';'') WHERE D.F_FORMAT = MS.F_FORMAT AND D.F_SECTION = MS.F_SECTION AND D.F_DEFAULT_CODE <> '''' AND (D.F_DATA_CODE = ''XGROUP'' OR D.F_DATA_CODE = L.F_DATA_CODE) AND REPLACE(D.F_DEFAULT_CODE,''|'','''') LIKE ''%''+L.F_TEXT_CODE+''%'') DS '
+CHAR(13)+CHAR(10)+' WHERE A.F_TEXT_CODE = L.F_TEXT_CODE '
+CHAR(13)+CHAR(10)+' AND (PT.F_TEXT_CODE IS NOT NULL OR PAT.F_TEXT_CODE IS NOT NULL OR CT.F_TEXT_CODE IS NOT NULL OR DS.DATA IS NOT NULL OR L.F_TEXT_TYPE = 1) '
+CHAR(13)+CHAR(10)+') '
+CHAR(13)+CHAR(10)+'ORDER BY ''Textcode in use'''
as 'Phrase Info: SQL script generated to run on client side'

/* Oracle Analysis */
SELECT 'SET DEFINE OFF;'
+CHAR(13)+CHAR(10)+'SELECT '
+CHAR(13)+CHAR(10)+'(SELECT COUNT(F_TEXT_CODE) FROM T_PROD_TEXT WHERE F_TEXT_CODE = L.F_TEXT_CODE) "In Products" '
+CHAR(13)+CHAR(10)+', (SELECT COUNT(F_TEXT_CODE) FROM T_PROD_ALIAS_TEXT WHERE F_TEXT_CODE = L.F_TEXT_CODE) "In Aliases" '
+CHAR(13)+CHAR(10)+', (SELECT COUNT(F_TEXT_CODE) FROM T_COMP_TEXT WHERE F_TEXT_CODE = L.F_TEXT_CODE) "In Components" '
+CHAR(13)+CHAR(10)+', (SELECT COUNT(D.F_DATA_CODE) FROM T_MSDSTYPE_SECTIONS MS JOIN T_DATATYPES D ON MS.F_FORMAT = D.F_FORMAT AND MS.F_SECTION = D.F_SECTION WHERE L.F_TEXT_CODE LIKE REPLACE(D.F_DEFAULT_CODE,''|'','''')) "In Defaults" '
+CHAR(13)+CHAR(10)+', L.F_DATA_CODE "Datacode in use" '
+CHAR(13)+CHAR(10)+', L.F_TEXT_CODE "Textcode in use" '
+CHAR(13)+CHAR(10)+', T.F_PHRASE "Current phrase" '
+CHAR(13)+CHAR(10)+', ''=INDEX(INDIRECT("B:B"),MATCH(INDIRECT(CONCAT("J",ROW())),INDIRECT("A:A"),0))'' "Reserved phrase" '
+CHAR(13)+CHAR(10)+', ''=EXACT(UPPER(INDIRECT(CONCAT("K",ROW()))),UPPER(INDIRECT(CONCAT("L",ROW()))))'' "Matches" '
+CHAR(13)+CHAR(10)+', ''=INDEX(INDIRECT(ADDRESS(MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),0),3,4)&":"&ADDRESS(IF(MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),1)=MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),0),MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),1),MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),1)),3,4)),MATCH(INDIRECT(CONCAT("K",ROW())),INDIRECT(ADDRESS(MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),0),2,4)&":"&ADDRESS(IF(MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),1)=MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),0),MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),1),MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),1)),2,4)),0),0)'' "Matching reserved datacode" '
+CHAR(13)+CHAR(10)+', ''=INDEX(INDIRECT(ADDRESS(MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),0),1,4)&":"&ADDRESS(IF(MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),1)=MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),0),MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),1),MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),1)),1,4)),MATCH(INDIRECT(CONCAT("K",ROW())),INDIRECT(ADDRESS(MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),0),2,4)&":"&ADDRESS(IF(MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),1)=MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),0),MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),1),MATCH(INDIRECT(CONCAT("I",ROW())),INDIRECT("C:C"),1)),2,4)),0),0)'' "Matching reserved textcode" '
+CHAR(13)+CHAR(10)+', ''=INDEX(INDIRECT("B:B"),MATCH(INDIRECT(CONCAT("O",ROW())),INDIRECT("A:A"),0))'' "Matching phrase" '
+CHAR(13)+CHAR(10)+', ''="UPD''||''ATE T_PROD_TEXT SET F_DATA_CODE = ''''"&INDIRECT(CONCAT("N",ROW()))&"'''', F_TEXT_CODE = ''''"&INDIRECT(CONCAT("O",ROW()))&"'''' WHERE F_DATA_CODE = ''''"&INDIRECT(CONCAT("I",ROW()))&"'''' AND F_TEXT_CODE = ''''"&INDIRECT(CONCAT("J",ROW()))&"''''"'' "Modify Products" '
+CHAR(13)+CHAR(10)+', ''="UPD''||''ATE T_PROD_ALIAS_TEXT SET F_DATA_CODE = ''''"&INDIRECT(CONCAT("N",ROW()))&"'''', F_TEXT_CODE = ''''"&INDIRECT(CONCAT("O",ROW()))&"'''' WHERE F_DATA_CODE = ''''"&INDIRECT(CONCAT("I",ROW()))&"'''' AND F_TEXT_CODE = ''''"&INDIRECT(CONCAT("J",ROW()))&"''''"'' "Modify Aliases" '
+CHAR(13)+CHAR(10)+', ''="UPD''||''ATE T_COMP_TEXT SET F_DATA_CODE = ''''"&INDIRECT(CONCAT("N",ROW()))&"'''', F_TEXT_CODE = ''''"&INDIRECT(CONCAT("O",ROW()))&"'''' WHERE F_DATA_CODE = ''''"&INDIRECT(CONCAT("I",ROW()))&"'''' AND F_TEXT_CODE = ''''"&INDIRECT(CONCAT("J",ROW()))&"''''"'' "Modify Components" '
+CHAR(13)+CHAR(10)+', (SELECT LISTAGG(MS.F_FORMAT||''/''||MS.F_MSDSTYPE||''/''||MS.F_SECTION,'', '') WITHIN GROUP (ORDER BY MS.F_FORMAT, MS.F_MSDSTYPE, MS.F_SECTION) FROM T_MSDSTYPE_SECTIONS MS JOIN T_DATATYPES D ON MS.F_FORMAT = D.F_FORMAT AND MS.F_SECTION = D.F_SECTION WHERE L.F_TEXT_CODE LIKE REPLACE(D.F_DEFAULT_CODE,''|'','''')) "Defaults in use" '
+CHAR(13)+CHAR(10)+'FROM ('+STUFF((
SELECT DISTINCT ' UNION ALL SELECT '''+D.F_DATA_CODE+''' CODE FROM DUAL'
FROM T_MSDSTYPE_SECTIONS M
JOIN T_DATATYPES D ON D.F_SECTION = M.F_SECTION AND D.F_FORMAT = M.F_FORMAT
JOIN T_GCS_RESERVED_DATA_CODES G ON G.F_DATA_CODE = D.F_DATA_CODE
WHERE M.F_FORMAT = @@Format@@
AND (M.F_MSDSTYPE = @@SubFormat@@ OR M.F_MSDSTYPE LIKE LEFT(@@SubFormat@@,LEN(@@SubFormat@@)-1)+'D' OR M.F_MSDSTYPE = 'GHSD')
ORDER BY 1 FOR XML PATH('')),1,11,'')+') DATA '
+CHAR(13)+CHAR(10)+'JOIN T_PHRASE_LINKAGE L ON L.F_DATA_CODE = DATA.CODE '
+CHAR(13)+CHAR(10)+'JOIN T_PHRASE_TRANSLATIONS T ON T.F_PHRASE_ID = L.F_PHRASE_ID AND T.F_LANGUAGE = ''EN'' '
+CHAR(13)+CHAR(10)+'LEFT JOIN ('+REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(STUFF((
SELECT DISTINCT ' UNION ALL SELECT '''+L.F_DATA_CODE+''' "D", '''+REPLACE(REPLACE(REPLACE(REPLACE(T.F_PHRASE,CHAR(39),CHAR(39)+CHAR(39)),'insert','ins''+''ert'),'update','up''+''date'),'delete','del''+''ete')+''' "P", '''+L.F_TEXT_CODE+''' "T" FROM DUAL'
FROM T_MSDSTYPE_SECTIONS M
JOIN T_DATATYPES D ON D.F_SECTION = M.F_SECTION AND D.F_FORMAT = M.F_FORMAT
JOIN T_GCS_RESERVED_DATA_CODES G ON G.F_DATA_CODE = D.F_DATA_CODE
JOIN T_PHRASE_LINKAGE L ON L.F_DATA_CODE = G.F_DATA_CODE
JOIN T_PHRASE_TRANSLATIONS T ON T.F_PHRASE_ID = L.F_PHRASE_ID AND T.F_LANGUAGE = 'EN'
WHERE M.F_FORMAT = @@Format@@
AND (M.F_MSDSTYPE = @@SubFormat@@ OR M.F_MSDSTYPE LIKE LEFT(@@SubFormat@@,LEN(@@SubFormat@@)-1)+'D' OR M.F_MSDSTYPE = 'GHSD')
ORDER BY 1 FOR XML PATH('')),1,11,''),'&amp;','&'),'&lt;','<'),'&gt;','>'),'insert','ins''+''ert'),'update','upd''+''ate'),'delete','del''+''ete')+') E '
+CHAR(13)+CHAR(10)+'ON E.D = L.F_DATA_CODE AND E.T = L.F_TEXT_CODE AND REPLACE(REPLACE(TO_CHAR(E.P),''&lt;'',''<''),''&gt;'',''>'') = TO_CHAR(T.F_PHRASE) '
+CHAR(13)+CHAR(10)+'WHERE E.T IS NULL '
+CHAR(13)+CHAR(10)+'AND EXISTS ('
+CHAR(13)+CHAR(10)+' SELECT 1 FROM T_PHRASE_LINKAGE A '
+CHAR(13)+CHAR(10)+' LEFT JOIN T_PROD_TEXT PT ON PT.F_DATA_CODE = A.F_DATA_CODE AND PT.F_TEXT_CODE = A.F_TEXT_CODE '
+CHAR(13)+CHAR(10)+' LEFT JOIN T_PROD_ALIAS_TEXT PAT ON PAT.F_DATA_CODE = A.F_DATA_CODE AND PAT.F_TEXT_CODE = A.F_TEXT_CODE '
+CHAR(13)+CHAR(10)+' LEFT JOIN T_COMP_TEXT CT ON CT.F_DATA_CODE = A.F_DATA_CODE AND CT.F_TEXT_CODE = A.F_TEXT_CODE '
+CHAR(13)+CHAR(10)+' CROSS JOIN T_MSDSTYPE_SECTIONS MS '
+CHAR(13)+CHAR(10)+' LEFT JOIN T_DATATYPES D ON MS.F_FORMAT = D.F_FORMAT AND MS.F_SECTION = D.F_SECTION AND L.F_TEXT_CODE LIKE REPLACE(D.F_DEFAULT_CODE,''|'','''') '
+CHAR(13)+CHAR(10)+' WHERE A.F_TEXT_CODE = L.F_TEXT_CODE '
+CHAR(13)+CHAR(10)+' AND (PT.F_TEXT_CODE IS NOT NULL OR PAT.F_TEXT_CODE IS NOT NULL OR CT.F_TEXT_CODE IS NOT NULL OR D.F_DATA_CODE IS NOT NULL OR L.F_TEXT_TYPE = 1) '
+CHAR(13)+CHAR(10)+') '
+CHAR(13)+CHAR(10)+'ORDER BY ''Textcode in use'''
as 'Phrase Info: Oracle script generated to run on client side'

/* LOLI script */
select 'SELECT * ' + CHAR(13)+CHAR(10) + 'FROM T_LOLI_WERCS_XREF_2 ' + CHAR(13)+CHAR(10) + 'WHERE F_WERCS_SS IN (' + STUFF((
SELECT DISTINCT ','''+L.F_WERCS_SS+''''
FROM T_LOLI_WERCS_XREF_2 L
JOIN T_DATATYPES D
ON D.F_Data_Code = L.F_WERCS_SS
JOIN T_Msdstype_Sections M
ON M.F_Format = D.F_Format
AND M.F_Section = D.F_Section
WHERE M.F_MSDSTYPE = @@SubFormat@@
OR M.F_MSDSTYPE LIKE LEFT(@@SubFormat@@,LEN(@@SubFormat@@)-1)+'D'
OR M.F_MSDSTYPE = 'GHSD'
ORDER BY 1
FOR XML PATH('')), 1, 1, '') + ');' + CHAR(13)+CHAR(10) + CHAR(13)+CHAR(10) 
UNION
SELECT 'UPDATE T_LOLI_WERCS_XREF_2 ' + CHAR(13)+CHAR(10) + 'SET F_MAP_USER_UPDATED = ''WPS'', F_MASK_USER_UPDATED = ''WPS'' ' + CHAR(13)+CHAR(10) + 'WHERE F_WERCS_SS IN (' + STUFF((
SELECT DISTINCT ','''+L.F_WERCS_SS+''''
FROM T_LOLI_WERCS_XREF_2 L
JOIN T_DATATYPES D
ON D.F_Data_Code = L.F_WERCS_SS
JOIN T_Msdstype_Sections M
ON M.F_Format = D.F_Format
AND M.F_Section = D.F_Section
WHERE M.F_MSDSTYPE = @@SubFormat@@
OR M.F_MSDSTYPE LIKE LEFT(@@SubFormat@@,LEN(@@SubFormat@@)-1)+'D'
OR M.F_MSDSTYPE = 'GHSD'
ORDER BY 1
FOR XML PATH('')), 1, 1, '') + ');'